### ISSUE TITLE
Redis connection gone from end event

### ISSUE THREAD

**Issue by kishore25kumar** [joeferner/redis-commander#101]
when i try to connect to a redis instance on my local box with the following command
redis-commander --redis-port 32004 --redis-host localhost

it gave the following error
path.existsSync is now called `fs.existsSync`.
listening on  8081
Connection closed. Attempting to Reconnect...
Redis connection gone from end event.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
