### ISSUE TITLE
Ability to add key:value pairs to existing and new hashes

### ISSUE THREAD

**Issue by jasonkeene** [joeferner/redis-commander#102]
There appears to be support for viewing/editing key:value pairs inside an existing hash but you can not create new key:value pairs (either for existing hashes or new hashes) w/o going down to the console and using hmset.

**Comment by berimor** [comment]
Is this feature going to be considered? It is crucial for us.

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
