### ISSUE TITLE
Expiring keys doesn't appear in list

### ISSUE THREAD

**Issue by jockster** [joeferner/redis-commander#109]
If I were to store an expiring key in redis as shown below and then open up/refresh redis-commander, the key doesn't appear. Is this intentional?

```
SET expiringkey 1234 => OK
EXPIRE expiringkey 3600 => OK
GET expiringkey => 1234
TTL expiringkey => 3600
```

**Comment by sseide** [comment]
The feature requested is available with latest version. If key is already expired while running "refresh" it is not listed anymore as redis commander does not know about it. All other keys not expired while opening/refreshing view are shown.

If there is something missing at the implementation feel free to reopen issue with an updated description.
