### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by goodgene** [joeferner/redis-commander#118]
I found the below exception case.

Is there a way to avoid this exception?

Or I guess you guys need to add lazy loading codes considering too many data.

thanks,

loading keys by prefix ""
found 81 keys for ""
loading keys by prefix ""
found 1079013 keys for ""

/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:525
            throw err;
                ^
RangeError: Maximum call stack size exceeded

**Comment by MiteshShah** [comment]
@goodgene Any update how did you fixed it ?

**Comment by mnuessler** [comment]
I think this issue has been closed by mistake. I accidentally referenced it in a PR commit message at first. I fixed the commit message, but still this issue was closed. Sorry for that..
