### ISSUE TITLE
I cannot connection it  if data too big 

### ISSUE THREAD

**Issue by ljcqx** [joeferner/redis-commander#119]
Redis Connection 192.168.0.246:6379 Using Redis DB #0
loading keys by prefix ""
found 4 keys for ""
loading keys by prefix ""
found 84385 keys for ""
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...
Connection closed. Attempting to Reconnect...

Always in the loaded state

**Comment by sseide** [comment]
same problem as #97
