### ISSUE TITLE
Redis-commander will stop itself after a while or if I log out my session.

### ISSUE THREAD

**Issue by marianogg9** [joeferner/redis-commander#120]
Hi there. 
Is it an expected behaviour? I run redis-commander, it goes up normally like 

path.existsSync is now called `fs.existsSync`.
listening on  8081
Redis Connection redis-server_host:6379 Using Redis DB X

but if I logout from the session it goes down.

I tried adding it to a supervisord, but it keeps on falling.

Any ideas? Thanks!!

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
