### ISSUE TITLE
Request: auto list databases and select from there

### ISSUE THREAD

**Issue by seansan** [joeferner/redis-commander#121]
Request: auto list databases and select from there

Hi, one of the reasons we would like to use the program is to identify which databases exist .. now we have to configure them ... 

Would it be an idea that the program auto detects which databases exist (within a port)

Thanks

**Comment by sseide** [comment]
its a long time since request but now available at latest docker image and github code...

**Comment by sseide** [comment]
fixed version 0.6.6 release to NPM too.
