### ISSUE TITLE
Not working as expected.

### ISSUE THREAD

**Issue by ceylon23** [joeferner/redis-commander#124]
We recently moved servers and tried installing 0.2.1 however it does not seem to be operating as expected. We are not able to use the in-browser cli and the css seems incorrect. The install went perfectly without any errors but when the page is loaded we receive 3 errors stating there are missing modules.

Error: Cannot find module 'readline-browserify'    browserify.js line 41
Error: Cannot find module 'cmdparser'    browserify.js line 41
TypeError: readline.createInterface is not a function    redisCommander.js Line 579

Are we missing some other dependent modules?

We did not have this trouble with v0.2.0.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
