### ISSUE TITLE
shutting down commander and restarting still connects to old host

### ISSUE THREAD

**Issue by levinotik** [joeferner/redis-commander#131]
First of all, awesome project. I use redis-commander extensively to keep an eye on things. The issue I'm experiencing is that when I shut down redis-commander and then restart it, specifying a new host, I still see it trying to connect to the old host (in addition to the new one). The logs show a failure to connect to an old instance I had running and I also see the old host as a blue button on the bottom of the UI. Also, when this happens, I can't seem to see any data displayed for the new instance. Is there a way to remove the old host?

**Comment by sseide** [comment]
Whenever redis commander is not startet with "--nosave" option (or param set inside config file) servers added successful are remembered.
You can remove these servers either by editing the config file, remove them via UI or start redis commander with "--clear-config" to forget all servers saved.

If there is something missing at the implementation feel free to reopen issue with an updated description.
