### ISSUE TITLE
SSL connection error

### ISSUE THREAD

**Issue by prasmalla** [joeferner/redis-commander#132]
cannot get it to work with https

**Comment by JulienBlancher** [comment]
+1

**Comment by mrichman** [comment]
I can't use SSL, and can't specify an alternate port (i.e. 6380). It will always try to connect via 6379.

**Comment by sseide** [comment]
Redis Commender does not support TLS/SSL encryption of it own. To secure the web ui put it behind a reverse proxy that does the TLS termination (nginx, apache, traefik,  ...).

And last comments seems to reverence some completly unrelated problem (HTTPS UI vs TLS secured Redis connection) which is working too with latest redis commander.

If you think its not fixed or something missing, feel free to reopen issue with updated informations based on latest version.
