### ISSUE TITLE
--redis-port not honoured

### ISSUE THREAD

**Issue by trevorbernard** [joeferner/redis-commander#133]
``` bash
redis-commander --redis-port 6380
No config found.
Using default configuration.
path.existsSync is now called `fs.existsSync`.
listening on  8081
Redis Connection 127.0.0.1:6379 Using Redis DB #0
```

**Comment by danielbprice** [comment]
I hit the same issue, it'd be really nice to have a fix.

**Comment by gabeio** [comment]
@nemesis sorry I didn't respond sooner I stopped using redis-commander but I will try again in the next month-ish and see if this is still an issue

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
