### ISSUE TITLE
Unable to Import back into REDIS

### ISSUE THREAD

**Issue by paranoid-android** [joeferner/redis-commander#136]
In redis Commander, I click "More... -> Export". I then choose my connection. I then choose "JSON". I then click "Export". A file named db.[someNumber].redis gets downloaded to my machine. Later, when I go to import this data, I'm unable to do so.

I click "More... -> Import".  I then choose my connection. There is a big text box. I was expecting a file upload button. Still, I open the file that I downloaded, copy the JSON to the clipboard, and paste it into the big text box. I then click "Import". When I do this, I get a success message that says 0 inserted and 0 errors. 

It seems that there isn't a way to re-import data after its been exported.

**Comment by fratuz610** [comment]
There is a bug (possibly multiple) in the way data is exported

I had to write a script to clean up the output

Also beware: when you reimport the data the whole dataset is dropped before the new import commences. If the latter operation fails you would have lost all the data

I will try and put together a pull request

**Comment by backendmaster** [comment]
Still no pull request?

**Comment by sseide** [comment]
My last pull request https://github.com/joeferner/redis-commander/pull/272 will fix the export/import when you run it inside a docker container. When running with simple git checkout you have to patch the used redis-dump library with the patch file provided (have a look at the Dockerfile line 21 for the exact command to run). I created a pull request for the redis-dump package too, but this is not merged as of now (https://github.com/EvilDevRu/node-redis-dump/pull/1)

At least the REDIS version of the import is working now. The library used by RedisCommander does not support import of JSON format (as far as i understand).

**Comment by sseide** [comment]
As said JSON import is not available from importer lib used, only REDIS commands are working.

For flushing database before importing, there is a configuration param (redis.flushOnImport) to either check or uncheck this checkbox per default. This can be set via ENV-var or cli param too. Will probably help the one or other...
