### ISSUE TITLE
Removing a server not possible

### ISSUE THREAD

**Issue by ghost** [joeferner/redis-commander#137]
UI does not offer removing a server

**Comment by shanabus** [comment]
Is there a way to do this from the command line for now?

**Comment by partycoder** [comment]
you can remove it from the `.redis-commander` file. this is what i did

**Comment by sseide** [comment]
The feature requested is available with latest version. It is possible after selecting the server entry in the tree view either with "disconnect" button or via right click on the tree entry.

If there is something missing at the implementation feel free to reopen issue with an updated description.
