### ISSUE TITLE
Ubuntu 14.04 vagrant box

### ISSUE THREAD

**Issue by unattended-user** [joeferner/redis-commander#153]
In official ubuntu 14.04 vagrant after running "npm install -g redis-commander" redis-commander will crash as soon as it's page is opened, unless run from /usr/local/lib/node_modules/redis-commander directory.

Output:

```
No config found or was invalid.
Using default configuration.
No Save: false
listening on  0.0.0.0 : 8081
Redis Connection 127.0.0.1:6379 Using Redis DB #0

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'cmdparser' from '/home/vagrant'
    at /usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by korun** [comment]
Same issue here!
Using Ubuntu 14.04 (3.13.0-43-generic)

**Comment by conorgil** [comment]
Same issue here.

**Comment by wesgurn** [comment]
Same here

**Comment by ellisthedev** [comment]
I have this same issue on CentOS 7. Appears the fix is to run:

`npm install -g cmdparser` and reload Redis Commander.

Forgotten dependency maybe?

**Comment by ellisthedev** [comment]
I spoke too soon. It randomly works. But eventually crashes. I don't get it.

Rolled back to 0.2.1 until this is fixed... Sigh.

**Comment by primael** [comment]
I've the same issue with debian 8, node v0.12.2 and npm v2.7.4

The command npm install -g cmdparser don't fix the problem.

**Comment by primael** [comment]
I've changed in package.json the version of browserify-middleware@3.0.0 to browserify-middleware@5.0.1 and that fixed the problem.

**Comment by tauren** [comment]
Any chance an `npm publish` could be done for version `3.0.1` that contains this fix?

**Comment by ellisthedev** [comment]
Yes, please! In the mean time you can run:

    npm install -g git+https://github.com/joeferner/redis-commander.git

**Comment by hstitz-jku** [comment]
@ellisthedev Thanks, this works for me.

**Comment by LakshminarayananKrishnan** [comment]
@ ellisthedev : It works fine, Thanx

**Comment by wesgurn** [comment]
Works for me as well :+1:

**Comment by spuder** [comment]
Also getting this error on OSX

```bash
sowens-MBP:~ sowen$ redis-commander
No config found or was invalid.
Using default configuration.
No Save: false
listening on  0.0.0.0 : 8081
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at HTTPServer.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
```

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.

The last comment does not show a bug in redis commander but another app already running at the request tcp port 8081. There can only be one app using a port at the same time
