### ISSUE TITLE
Redis UI Control: Cannot change the size of the window containing key names

### ISSUE THREAD

**Issue by pankaj3009** [joeferner/redis-commander#156]
The redis commander: home page displays the keys on the left. I have keys of a large size, and unfortunately i cannot drag out the window on the left. The drag icon is displayed when i hover the mouse on the edge of the window, but i cannot increase the size of the window..tried on explorer and chrome.

**Comment by rasekar2000** [comment]
This is very important.. I could not see the top section at all..

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
