### ISSUE TITLE
As a service or deamon on CentOS

### ISSUE THREAD

**Issue by basarolgun** [joeferner/redis-commander#158]
Hi,

I want to use Redis-Commander as a service or deamon on CentOS, how can it be possible? I found Ubuntu's script, is there any guide or document to achive this on CentOS? Thank you!

**Comment by emcniece** [comment]
Any chance you could link the Ubuntu script?

**Comment by radius314** [comment]
what version of CentOS?

**Comment by marianogg9** [comment]
+1 for CentOS 7

**Comment by radius314** [comment]
I have gotten this running with systemd

**Comment by sseide** [comment]
added an example systemd service description too for reference. Must be adapted locally as needed.
