### ISSUE TITLE
where is the config file?

### ISSUE THREAD

**Issue by roblav96** [joeferner/redis-commander#163]
anyone know?

I opened a new connection and now it keeps trying to connect to my old session. wtf

**Comment by roblav96** [comment]
in the home folder. use this if it breaks:
```
{"sidebarWidth":"250","locked":"false","CLIHeight":"420","CLIOpen":"true","default_connections":[{"label":"local","host":"127.0.0.1","port":"6379","password":"","dbIndex":"0"}]}
```
Cheers.

**Comment by exceeder** [comment]
For the people searching for the config file with unwanted connections, try `cat ~/.redis-commander`.

**Comment by sseide** [comment]
As this ticket refers to the old config file not used anymore it will be closed to not distract new users.
New configuration files can be found inside `config` folder of the app. To fully understand the new possiblities of the config folder please refer to https://github.com/lorenwest/node-config
