### ISSUE TITLE
Is there anyway to make the redis commander readonly to redis db or setup a password to visit?

### ISSUE THREAD

**Issue by zhang8473** [joeferner/redis-commander#170]
If I public the redis commander 8081 port to the public net, everyone can come and modify my db. Currently, I do not want to setup a password to my db because I have to do extra work on my API.
So, it there anyway to setup an account in redis commander? or simply disable writing permit in redis commander's configure?

**Comment by scragg0x** [comment]
It should support http auth

``` 
 --http-auth-username, --http-u  The http authorisation username.   [string]
 --http-auth-password, --http-p  The http authorisation password.   [string]
```

**Comment by sseide** [comment]
another issue with read-only mode request #341

**Comment by sseide** [comment]
Hi, i updated redis-commander to allow starting in read-only mode. It would be nice if someone could give it a try and check if its working as expected or if i missed something...

Currently only in git branch read-only-mode, no Docker images. Thought some more test might be good before merging...

Feedback welcome!

**Comment by sseide** [comment]
merged it into master, docker image with read-only support will show up soon...

**Comment by sseide** [comment]
Version with read-only mode release to npm too (0.6.3).

Now you can either add HTTP-Authentication and/or set Redis-Commander to read-only mode. If you find some problems with latest version, please create a new issue.

Thanks
