### ISSUE TITLE
Using SCAN instead of KEYS

### ISSUE THREAD

**Issue by behrad** [joeferner/redis-commander#171]
I like redis-commander, it's easy & powerful. However I can't run it against a production redis instance with a huge DB size, since it is using KEYS command to load/delete keys.

Will them be refactored to SCAN any soon?

**Comment by SebastienTainon** [comment]
See also this to specify patterns avoiding loading all database: https://github.com/joeferner/redis-commander/pull/197

**Comment by sseide** [comment]
The feature requested is available with latest version. Start redis commander with `--use-scan` cli param, set `USE_SCAN` env var or set this param inside your config file (`redis.useScan`)

If there is something missing at the implementation feel free to reopen issue with an updated description.
