### ISSUE TITLE
password protected db access

### ISSUE THREAD

**Issue by cyberpay** [joeferner/redis-commander#177]
**when i try to access password protected redis db using this command**

`redis-commander --redis-host 127.0.0.1 --redis-port 6379 --redis-password PASSWORD -p 2165 --http-u USERNAME --http-p password`

**im getting following error** 

```
No Save: false
listening on  0.0.0.0 : 2165
{ name: 'ReplyError',
  message: 'NOAUTH Authentication required.',
  command: { name: 'select', args: [ '0' ] } }
```

**edit:**
when i go in redis-cli and use AUTH password; redis authenticated my session. i did uninstall commander and installed it with -g (global) flag however error reproduced. 
any words of advice!!!

**Comment by scragg0x** [comment]
make sure you do `--redis-password`

you have a single `-`

**Comment by cyberpay** [comment]
no same error, i am using correct syntax might missed here while typing :)

**Comment by ameliaholcomb** [comment]
Same problem. And possibly related to https://github.com/joeferner/redis-commander/issues/179?

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
