### ISSUE TITLE
redis-commander behind nginx endpoint.

### ISSUE THREAD

**Issue by cpgravlee** [joeferner/redis-commander#181]
The issue that I am having is putting redis-commander behind NGINX at a specific endpoint.  Other tools are hosted behind the same NGINX server and all live behind their own endpoint.  I have done research on setting a base URL in Node JS but have not been able to come up with a solution that works.  Does anyone know of a way to alter redis-commander to allow for this specific need?

e.g.

location /redis-commander/ {
         proxy_pass http://redis-commander:8081;
}

**Comment by aadlung** [comment]
Would support this too, it seems that redis commander just uses relative URLs for assets like /css/, /scripts/, which you would have to pass to the proxy too. Just works if there are no other sites on nginX using this paths

**Comment by marcopeg** [comment]
I got it partially working:

```

# Learning Docker
# by @thepeg
# https://github.com/marcopeg/learning-docker

events {}

http {

    upstream redisui {
        server redis_ui:8081;
    }

    server {
        listen 8888;

        # Set proxy headers for the passthrough
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            proxy_pass http://redisui/;
        }
    }

}

```

My problem now are the linked assets (css, js) which are linked with an absolute path, so I can not proxy it with ta regular expression or something

**Comment by aadlung** [comment]
Sure, the proxy_pass stuff works out of the box. You can either work on the /usr/lib/node_modules/redis-commander/web/view/layout.ejs and change the paths to relative ones (might then need to adapt nginx too).

But that's exactly what I could not manage. The HTML code came through, but the assets (loaded from /css or even from /redis/css) did not work.

**Comment by mnuessler** [comment]
I have created PR #187 that changes all URLs to relative ones.
