### ISSUE TITLE
redis-commander --redis-host=remote_ip --redis-port=remote_port

### ISSUE THREAD

**Issue by Somebi** [joeferner/redis-commander#188]
This feature not working. Instead of connecting to remote host it is connecting to localhost redis...

**Comment by patmigliaccio** [comment]
It seems that it's saving a config file of the connections you've used prior with [this method](https://github.com/joeferner/redis-commander/blob/master/bin/redis-commander.js#L156) and then reading them into `config.default_connections` [here](https://github.com/joeferner/redis-commander/blob/master/bin/redis-commander.js#L102) when you start the app up again. In `startDefaultConnections`, it [loops over all](https://github.com/joeferner/redis-commander/blob/master/bin/redis-commander.js#L102) of the default connections, attempting to connect once again to a Redis server on your localhost. 

To fix this issue, although the current implementation of it isn't ideal, all you need to do is locate the `.redis-commander` file in your Home directory, in my case `~/.redis-commander`, and remove *all* of the objects from the `default_connections` array.

Hope this will help someone else with the issue until a refactoring is done to solve the problem.

**Comment by esynaps** [comment]
No file .redis-commander, the command ignore the --redis-host option

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
