### ISSUE TITLE
auth doesn't work when password contains an exclamation point

### ISSUE THREAD

**Issue by flashape** [joeferner/redis-commander#190]
Hi, it seems I can't connect if my password contains an exclamation point, such as "any!thing".

**Comment by adrian-gierakowski** [comment]
I believe password doesn't work at all, might be due to changes in ioredis

**Comment by krisklosterman** [comment]
I think adrian is right... no password seems to work :(

**Comment by sseide** [comment]
Passwords are working with latest version. As this bug report is not clear about wether http web ui password is meant or redis connection password just try the following for the password in question.

1) set password insisde your own config file, as these are json based there will be no problem.
2) when providing passwords via environment variables or command line params make shure to correctly quote the password as "!" has a special meaning for the shell starting the app (e.g. use single quotes around it or similiar)
