### ISSUE TITLE
Web interface won't recognise UPPERCASE commands

### ISSUE THREAD

**Issue by akashagarwal7** [joeferner/redis-commander#194]
If I type `KEYS *` it tells me its invalid command, while `keys *` works. However tab complete shows and inserts uppercase commands. The same is true for other commands. Running it on OS X Sierra.

**Comment by tyagiarpit** [comment]
Fixed

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
