### ISSUE TITLE
Log displays wrong DB index

### ISSUE THREAD

**Issue by Jiia** [joeferner/redis-commander#195]
The DB selection is working, but the console says it's `Using Redis DB #0` even though it's actually using another DB.  So just a minor bug there.

**Comment by Jiia** [comment]
The web interface also displays the wrong DB index. It's impossible to tell what db redis-commander is using.

**Comment by tyagiarpit** [comment]
Easy fix is to update db index in $HOME/.redis-commander file

**Comment by SeanC2222** [comment]
I don't know the full extent of this, but at least when it's reading in the default configuration the redisConnection.options.db is never _actually_ being set (or when it's being attempted it's not working right). I inserted "redisConnection.options.db = db" immediately prior to the .once() call  in redis-commander.js in function setUpConnection() and it both fixed the "logging issue" but actually fixed the functionality.
![screen shot 2017-07-28 at 11 18 44 am](https://user-images.githubusercontent.com/9671522/28730952-d400481e-7386-11e7-8617-00477ec48d0b.png)
![screen shot 2017-07-28 at 11 19 09 am](https://user-images.githubusercontent.com/9671522/28730957-d8747a28-7386-11e7-9c4c-16b87af42cd8.png)

**Comment by SeanC2222** [comment]
@Jiia I think I fixed the issue. Get the updated version and close this issue if you are no longer experiencing any problems.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
