### ISSUE TITLE
Feature request: custom key namespacing delimiter

### ISSUE THREAD

**Issue by tkalfigo** [joeferner/redis-commander#198]
Currently the default delimiter for the namespacing of the keys in jstree, is the ':' i.e. the one used by convention in Redis.

Any chance we can have this be configurable? We use ISO8601 timestamps as part of our keys, and the ':' is the time field separator.

**Comment by matyunin** [comment]
@joeferner It's actual for me too. We use Symfony framework (php) and their cache component implements PHP's [PSR-6 standard](http://www.php-fig.org/psr/psr-6), whose denies symbols `{}()/\@:` as [key](http://www.php-fig.org/psr/psr-6/#definitions).

We need custom namespacing key delimiter 🙏

**Comment by juanecabellob** [comment]
+1 for this feature! would help us a lot

**Comment by sseide** [comment]
I implemented this feature short time ago - please check it out at current github repo or docker image.
You can choose nearly every character as folding char (only excluded &?* to prevent some other errors).

If things work as needed please colse tihs issue...

**Comment by tkalfigo** [comment]
Confirmed it works on github repo code. 

Hope you release a new version on npm as well. 

Closing issue.
