### ISSUE TITLE
Getting an error while running redis-commander

### ISSUE THREAD

**Issue by babupca** [joeferner/redis-commander#202]
Hi All,

I could not able run the redis-commaner, it is throwing the below error.

Could you some faced this type of error, please help.

![redis-commander](https://user-images.githubusercontent.com/2504343/27735493-8ab0d8f6-5dbd-11e7-8825-72c4b7170b43.png)

**Comment by webdevian** [comment]
The port 8081 is already in use. Do you have another instance of redis-commander running somewhere else or another application listening on port 8081?

**Comment by sseide** [comment]
This is no error in redis commander but another app running at the same tcp port at the same time.
Its expected behaviour for this case - only one app at a time can use the port 8081
