### ISSUE TITLE
Commands from loaded modules not working

### ISSUE THREAD

**Issue by skeep** [joeferner/redis-commander#210]
No sure if I am doing this wrong but didn't find any relevant document hence opening a issue.
I have loaded http://rejson.io/commands/ which have extra commands.

When I use the command in redis-cli it works. However in web-interface it says **Invalid Command**.

```
> JSON.SET foo . '"bar"'
  ERROR: Invalid Command
```

**Comment by schwab** [comment]
I can confirm this happens with other modules too... for instance redis graph commands issued in redis-commander do the same thing ```GRAPH.QUERY test 'MATCH (d:dim_date) RETURN COUNT(d)'
ERROR: Invalid Command``` whereas the same command on the cli works fine.  Is there something more that needs to be done to support modules in redis-commander?

**Comment by sseide** [comment]
All valid commands for the web cli are defined inside the redisCommander.js file starting at line 973.
If there are additional modules loaded at the redis server this one must be redefined.

https://github.com/joeferner/redis-commander/blob/5519537d2b6b77786bd3e1a7dfca33ff14549f73/web/static/scripts/redisCommander.js#L973-L980

A possible solution may be to refactor this list to an external file and people needing non-standard commands can 
a) create their own docker images where they overwrite this file with their own command list or
b) add additional command sets/files which can be (somehow) activated via command parameters during redis-commander startup.

**Comment by sseide** [comment]
Due to my work of adding a read-only mode i now understand it a bit better...

The old client side list with commands was only used to add auto-completion with `TAB`. All commands are send to server and it tries to execute them.

Therefore `graph.query` should work inside cli.. Does "ioredis" support the extension? "ioredis" is the database driver used. I have no server to test it against and no time to dig deeper - but if you can help here?

Now i moved the definition of the command list from client to server side. It is used for cli auto-completion and - with read-only mode - as a white list of allowed commands. Did this as a preparation to allow definition of different sets of commands allowed... Will change hard-coded whitelist late to `command info` command where supported. Hard-coded white list as fallback then and for auto-completion..

**Comment by schwab** [comment]
That is strange.  I just tried this with commander and the cli.  What works in the cli always gives an error : ```graph.query graph:ortho "MATCH (f:fact_ortho) RETURN count(f)"
ERROR: Invalid Command```  But the same query on the cli... ```redis-graph:6379> graph.query graph:ortho "MATCH (f:fact_ortho) RETURN count(f)"
1) 1) 1) "count(f)"
   2) 1) "8699.000000"
2) 1) "Query internal execution time: 4.764779 milliseconds"
```  Perhaps there is something else we need to do on the commander configuration?

**Comment by sseide** [comment]
I have create a new branch "redis-commander-210" - can you please do a checkout, run `npm install` and check if the `graph.query` command works there via cli? removed the check for builtin commands...

And second one - can you please run `command` via redis-cli to send me a list with the output from a server with plugin enabled? Want to check if plugin commands are listed there to build command list on-the-fly...

**Comment by schwab** [comment]
Ok, ... 210 installed locally and tested with a graph command...

```
graph.query graph:ortho "MATCH (f:fact_ortho) RETURN count(f)"
1) count(f),8699.000000
2) Query internal execution time: 5.812511 milliseconds
```
So, it's working correctly in this version.  Nice!
Also here's some relavent output from "command" (actually run from redis-commander against a redis-graph enabled service...)
```command
1) swapdb,3,write,fast,0,0,0
2) restore,-4,write,denyoom,1,1,1
3) echo,2,fast,0,0,0
4) sadd,-3,write,denyoom,fast,1,1,1
5) hgetall,2,readonly,random,1,1,1
6) info,-1,random,loading,stale,0,0,0
7) zrange,-4,readonly,1,1,1
8) substr,4,readonly,1,1,1
...
77) graph.QUERY,-1,write,denyoom,noscript,1,1,1
...
163) graph.DELETE,-1,write,noscript,1,1,1
...
etc
```

**Comment by sseide** [comment]
New version at docker hub (0.6.4-rc1) and master branch has the fix needed to allow all commands available to the redis server.

And running in read-only mode it tries to build the list of allowed commands on the fly after connecting to the server. Therefor plugin commands will work too.

**Comment by sseide** [comment]
v0.6.4 release to NPM too. Will close as there are no new error reports...
Thanks
