### ISSUE TITLE
Show TTL for key

### ISSUE THREAD

**Issue by cen1** [joeferner/redis-commander#211]
When you open a key it would be nice if TTL would be displayed somewhere.

**Comment by ergunp** [comment]
TTL shown as -1 on UI.

here is my redis cli
`127.0.0.1:6379> get sessionStateCache::10.36.55.1
"\xac\xed\x00\x05sr\x00*sky.wifi.sessionmanager.model.SessionStatej\x93\xaa\xcd\tk\xc6\x8d\x02\x00\x02L\x00\x02idt\x00\x12Ljava/lang/String;L\x00\x13protocolRestrictiont\x00\x13Ljava/lang/Boolean;xpt\x00\n10.36.55.1sr\x00\x11java.lang.Boolean\xcd r\x80\xd5\x9c\xfa\xee\x02\x00\x01Z\x00\x05valuexp\x00"
127.0.0.1:6379> ttl sessionStateCache::10.36.55.1
(integer) 771`

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
