### ISSUE TITLE
Use custom redis config = Redis-Commander stay in loop of errors - Why?

### ISSUE THREAD

**Issue by MichelDiz** [joeferner/redis-commander#215]
For reference https://github.com/RedisLabsModules/RediSearch/issues/144

Every time I use a Docker image and give any command that changes or location or "reaffirm it" the location Redis-Commander and others can not connect anymore.

Using the image "stevenaldinger / redis-commander: latest" from this https://github.com/tenstartups/redis-commander-docker - And making my personal modifications happens the same. And when I try to just (even a clean image, docker without custom configs) I expose the port to the host just the Redis container. Redis-Commander (Docker container) goes "insane" (lost connection), as if I could not expose the port at any time.

For example:

Docker Redis (exposing port 6379: 6379 or 6379: random) + Docker Redis-commander
Windows with Medis or even Redis-Commander installed by NPM.

Don't work.

I can not use it, because all three begin to give errors. Medis does not say anything at all, just says there is an error. And Redis-Commander says it did not find Config file. And let nothing do and the interface breaks. The log is looped reporting error.

**Comment by sseide** [comment]
If poblem exists with latest version please give some moe informations how to exaclty reproduce as well as error messages printed by redis commander.

**Comment by sseide** [comment]
Close as ticket is unclear and no further feedback available.

If problem exists feel free to reopen with exact error messages from current Redis Commander version as well as current test setup.
