### ISSUE TITLE
redis-commander occasionally refreshes my session (express-session)

### ISSUE THREAD

**Issue by whoyawn** [joeferner/redis-commander#217]
OS: Mac OS
After every 2 or 3 requests, redis uses a different session and provides me a new key. This only occurs when I use redis-commander. If I use a different management application, like [medis](https://github.com/luin/medis), the I never get that problem. Does redis-commander have some method that refreshes the redis client? I don't see why this should be happening. Does anyone else ever get this problem? It's difficult to replicate this because the session refreshes I get are very inconsistent. Sometimes it persists, sometimes it doesn't.

**Comment by tylerong** [comment]
I've also encountered this problem.
It seems redis-commander's session ID overwrites my project's session ID stored in Cookie.
For a workaround, changing your session ID name from "connect.sid" or accessing redis-commander from other browsers.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
