### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by AlmogBaku** [joeferner/redis-commander#218]
How do I enable TLS support?

**Comment by AlmogBaku** [comment]
@joeferner

**Comment by sseide** [comment]
What do you mean with TLS support?
* Client side - access via HTTPS? Not supported - use reverse proxy in front of redis commander (e.g. nginx)
* TLS secured redis connections? Supported with PR #339. Available via git checkout or docker image.
Not available via `npm install` right now...

**Comment by sseide** [comment]
Version with TLS support release to NPM too, will close issue as this should be resolved by now. Feel free to reopen and provide additional information to describe your problem if needed.
