### ISSUE TITLE
How to install redis-commander in cPanel

### ISSUE THREAD

**Issue by Nirjonadda** [joeferner/redis-commander#225]
Please let me know that How to install redis-commander in cPanel on CentOS 7.4?

**Comment by sseide** [comment]
Installation is either done via commad line with git checkout where you must take care to automatically start it on system reboot (can be done via cPanel SSH access if avail) or installed as docker container if cPanel provides such a thing.

There is no simple file upload or ready-to-go cpanel plugin (but feel free to provide one).
