### ISSUE TITLE
Http authorization in docker evnironment? 🔑

### ISSUE THREAD

**Issue by binakot** [joeferner/redis-commander#231]
README contains Docker section with information about template `label:hostname:port:dbIndex:password` which is using in `REDIS_HOSTS` environment variable. How can I use this one to add user authorization (login and password for web ui).

I see parameters `--http-u` and `--http-p` for application itself. But there is no anything about these in [entrypoint.sh](https://github.com/joeferner/redis-commander/blob/master/docker/entrypoint.sh).

Also I found few docker images that try to solve this problem, but they are deprecated (last activity 1+ years ago). I can create one more image for ur project, and after few month it will deprecate too 😁

Is it possible to replace this template with `:` separation to specific ENV variables like:
* REDIS_PORT
* REDIS_HOST
* REDIS_PASSWORD
* HTTP_USER
* HTTP_PASSWORD
* etc...

Please, update your docker image with ENV variables 😋

Or if not, tell me why and how can I put http auth variables to docker-compose file in environment section.

Thanks and cheers ❤️

**Comment by binakot** [comment]
This is the list of projects that just try to add ENV variables:
* https://github.com/higebu/docker-redis-commander
* https://github.com/emmenko/docker-redis-commander
* https://github.com/dmportella/docker-redis-commander
* https://github.com/tenstartups/redis-commander-docker
* https://github.com/osado/redis-commander
* https://hub.docker.com/r/dapda/redis-commander

**Comment by binakot** [comment]
Awesome! ☕️ 🍪

**Comment by cen1** [comment]
Maybe I am missing something but this does not seem to work.. my compose:
```
 environment:
      - REDIS_HOSTS=local:redis-container:6379
      - HTTP_USER=user
      - HTTP_PASSWORD=pass
```

Result: no auth prompt
