### ISSUE TITLE
Multiple connections to the same instance with different DBs not working

### ISSUE THREAD

**Issue by tburschka** [joeferner/redis-commander#236]
Hello,

I'm try to run the docker container with the REDIS_HOSTS env variable witch looks like this:

```
REDIS_HOSTS='dev:redis:6379:0,test:redis:6379:10'
```
but it seems that the given database is ignored, since the UI shows me for both connections the database 0. This leads to an instable system, since after you click on one of the two connections the the view stucks on "loading ...." instead of showing the connection parameters.

**Comment by hirnschmalz** [comment]
I also tried to configure multiple connections via `REDIS_HOSTS` environment variable. No luck for me too.

The **undefined** entries at the bottom are also a bit irritating.

![image](https://user-images.githubusercontent.com/4834988/36982249-b5383bc4-208f-11e8-8bf0-eeb6640b9b9f.png)

**Comment by tburschka** [comment]
@hirnschmalz You are right, i've seen this too but i forgot to mentioned the undifined fields

**Comment by hirnschmalz** [comment]
@tburschka The latest image solved this issue

**Comment by hirnschmalz** [comment]
@joeferner This issue is back in the latest docker image. 👎 
Seems to be an issue with the with the change of the namespace `@awearsolutions/redis-commander`. It's a bit annoying to create a PR to fix a problem which is back one version later.

**Comment by sseide** [comment]
Should be working with latest github/docker versions. At least we use it without any problem...
Can issue be closed?

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
