### ISSUE TITLE
wildcard in key name causing graphical glitch

### ISSUE THREAD

**Issue by alongley** [joeferner/redis-commander#239]
the following commands run against Redis:
set abcdefghijk:abcdefghijk 123
set abc*:abcdefghijk 123
and then viewed in Redis-commander presents a graphical glitch where it appears that the wildcarded key, e.g. abc*, has a ghost child of 'fghijk'.
I assume this has to do with the 'keys' command. According to the docs, 
keys abc\\* should escape the asterisk but it does not seem to.
I don't think the Redis db is corrupt, I think it's a display issue with Redis-commander. Curious if my interpretation is wrong or if there's a simple solution. Thanks.

**Comment by alongley** [comment]
Spent some more time on this. 
Given the scenario above with the two keys, invoking the following produces the following output:
- in redis-commander:
  keys abc\*:* or keys "abc\*:*" produces 2 keys
- in redis-cli:
 redis-cli keys abc\*:* produces 2 keys
 redis-cli keys "abc\*:*" produces 1 key
- in node-redis
  redisClient.keys("abc\\*:*") produces 1 key

If I alter lib/routes/apiv1.js line 643 from, to
--    search = prefix + foldingCharacter + '*';
++   search = prefix.replace("*", "\\*") + foldingCharacter + '*';

I get the behavior in redis-commander I expect. This seems to fix the GUI. It does not affect the REST endpoint associated with the keys command, /apiv1/keys or /apiv1/keystree.

**Comment by atuttle** [comment]
https://github.com/joeferner/redis-commander/blob/e80cdc16714b0b4ebc12d10fe588e4a40343cea9/lib/routes/apiv1.js#L676

Looks like this change has been made. Recommend closing this issue.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
