### ISSUE TITLE
Can't select specific db while 'add server'.

### ISSUE THREAD

**Issue by codejie** [joeferner/redis-commander#240]
When try to add server with specific db, commander always selects db '0'.
I reviewed source code, maybe should add the below line at app.js:101

client.options.db = dbIndex;

Right?

**Comment by styfle** [comment]
It kind of works for me if I use the `--redis-db 1` flag but the display still shows `0`.

Also I can't seem to connect to two databases at once.

**Comment by sseide** [comment]
Problem exists or fixed by now? If fixed, please close...

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
