### ISSUE TITLE
Add connection name

### ISSUE THREAD

**Issue by jstoja** [joeferner/redis-commander#242]
Having a connection name when redis-commander connects to Redis is nice so you know which connection is from which application.
The Redis command is here: https://redis.io/commands/client-setname
And the `ioredis` API option is here: https://github.com/luin/ioredis/blob/master/API.md#Redis (`[options.connectionName]`).

I think that would be a great addition, I can PR it if wanted.

**Comment by sseide** [comment]
please create a PR, this is a good idea.

**Comment by jstoja** [comment]
@joeferner This can be closed now ;)
