### ISSUE TITLE
sidebar tree uses "folder" to represent tree

### ISSUE THREAD

**Issue by ozomer** [joeferner/redis-commander#246]
For example, if you run:
```
set mykey 1
set mykey:mysubkey 2
```
You get a "folder" called `mykey:*` - clicking this folder will show you the value of `mykey`, even though it does not start with the prefix `mykey:`.
In my opinion, `mykey` should be represented in a different node in the tree, separated from the `mykey:` folder.

**Comment by sseide** [comment]
is working now - can be closed?
