### ISSUE TITLE
RedisCommander does not work with password protected databases

### ISSUE THREAD

**Issue by sseide** [joeferner/redis-commander#247]
started with docker image "rediscommander/redis-commander:latest" no connection is possible to password protected databases.

<pre>
sudo docker run --env REDIS_HOSTS=vm:192.168.20.20:6379:0:secretpass -p 8081:8081 rediscommander/redis-commander:latest
</pre>

starting docker image via this command gives the following error:
<pre>
Creating custom redis-commander config.
Configuration:
{
  "sidebarWidth":250,
  "locked":false,
  "CLIHeight":50,
  "CLIOpen":false,
  "default_connections": [
      {
        "label":"vm",
        "host":"192.168.20.20",
        "port":"6379",
        "password":"secretpass",
        "dbIndex":0
      }
  ]
}
node /usr/bin/redis-commander 
No Save: true
listening on  0.0.0.0 : 8081
{ ReplyError: NOAUTH Authentication required.
    at ReplyParser._parseResult (/usr/lib/node_modules/redis-commander/node_modules/ioredis/lib/parsers/javascript.js:39:14)
    at ReplyParser.execute (/usr/lib/node_modules/redis-commander/node_modules/ioredis/lib/parsers/javascript.js:139:20)
    at Socket.<anonymous> (/usr/lib/node_modules/redis-commander/node_modules/ioredis/lib/redis/event_handler.js:94:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
  name: 'ReplyError',
  message: 'NOAUTH Authentication required.',
  command: { name: 'select', args: [ '0' ] } }
</pre>

removing the "requirepass secretpass" parameter from the redis server configuration and removing the password from the docker startup command too the rediscommander can connect without problem. As soon as a password is set the connection does not work anymore...

**Comment by alaexeyshustov** [comment]
Have the same issue.
It seems that issue was created by - https://github.com/joeferner/redis-commander/pull/244

**Comment by wolmi** [comment]
Maybe you can use my image that the fixes it on PR #258 

https://hub.docker.com/r/wolmi/redis-commander/

**Comment by sseide** [comment]
thanks - using latest version from master with PR #258 i'm able to connect to password protected redis.

**Comment by cgunnels** [comment]
@wolmi how does you're image fix the issue? I don't see the difference.

**Comment by wolmi** [comment]
You can see the difference on the diff from the PR https://github.com/joeferner/redis-commander/pull/258 

The main difference is to use correctly the package.json to install correctly the dependencies with the right versions.

**Comment by jessequinn** [comment]
For me this issue still persists @wolmi with your image. Any ideas?

redis:6.0.8-alpine
wolmi/redis-commander:latest
