### ISSUE TITLE
password length can be leaked

### ISSUE THREAD

**Issue by deian** [joeferner/redis-commander#261]
From looking at your usage of timingSafeEqual I think you'd be leaking the length of the password; IMO timingSafeEqual should handle different length buffers, but thought I'd bring this up.

https://github.com/joeferner/redis-commander/blob/70ead63a47157267a129fbce2ecd5c0a3b237b91/lib/app.js#L25-L31

More seriously:

https://github.com/joeferner/redis-commander/blob/70ead63a47157267a129fbce2ecd5c0a3b237b91/lib/app.js#L22-L24

will always be `true` (typo: timeingSafeEqual) and you're using `==`

**Comment by sseide** [comment]
fixed with pull request #275 - can be closed?
