### ISSUE TITLE
Please update bcrypt dependency

### ISSUE THREAD

**Issue by ozomer** [joeferner/redis-commander#266]
Bcrypt 1.0.3 might throw Segmentation Faults when used in Kubernetes.

See: https://github.com/kelektiv/node.bcrypt.js/issues/528

**Comment by sseide** [comment]
will be updated with my pull request #268 along other issues...

can you please check if this fixes your problems with kubernetes?

**Comment by ozomer** [comment]
I'm sure it will work. Already tested this with other packages that used bcrypt.
