### ISSUE TITLE
Unable to connect with socket

### ISSUE THREAD

**Issue by arnaudhb** [joeferner/redis-commander#270]
If redis server is started with socket, redis-commander cannot connect and fails with RangeError.

Server:
```
$> redis-server --unixsocket /tmp/redis.sock --port 0
```
Redis-commander:
```
$> redis-commander -p 9000 --clear-config --redis-socket /tmp/redis.sock
...
net.js:1064
      throw new RangeError('"port" option should be >= 0 and < 65536: ' + port);
      ^

RangeError: "port" option should be >= 0 and < 65536: NaN
    at lookupAndConnect (net.js:1064:13)
    at Socket.connect (net.js:1037:5)
    at Object.connect (net.js:113:35)
```

It seems the socket path is not forwarded to the Redis client:
https://github.com/NodeRedis/node_redis#rediscreateclient

**Comment by sseide** [comment]
Should be fixed with latest version from github and docker image. NPM release will come later.

**Comment by joeferner** [comment]
published 0.6.4 can you verify this fixes the probelm

**Comment by hackhowtofaq** [comment]
```
./redis-commander.js --redis-socket /tmp/redis.sock
internal/crypto/hash.js:33
  this._handle = new _Hash(algorithm);
                 ^

Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:33:18)
    at Object.createHash (crypto.js:101:10)
    at Object.createRedisClient (/home/gamma/projects/redis_managers/redis-commander/lib/util.js:320:23)
    at /home/gamma/projects/redis_managers/redis-commander/bin/redis-commander.js:370:26
    at startDefaultConnections (/home/gamma/projects/redis_managers/redis-commander/bin/redis-commander.js:416:10)
    at startAllConnections (/home/gamma/projects/redis_managers/redis-commander/bin/redis-commander.js:336:3)
    at Object.<anonymous> (/home/gamma/projects/redis_managers/redis-commander/bin/redis-commander.js:282:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by sseide** [comment]
@hackhowtofaq Operating System? Node version? How installed?

**Comment by hackhowtofaq** [comment]
> @hackhowtofaq Operating System? Node version? How installed?

OS: Mint Linux 19.1
Node: v10.15.3
How installed: git clone repo + yarn

**Comment by sseide** [comment]
thanks - latest 10.x node dropped support for 'sha' algorithm it seems. Pushed update to select algorithm from list of available ones.

btw - as README states installation via `yarn` not supported - you will run into problems later on. Please use `npm` for installation.

**Comment by Vincent-CIRCL** [comment]
Hi,
Same problem ("Digest method not supported at new Hash (internal/crypto/hash.js:39:19)" even with last version of the repository.
Would you have more detail about "Pushed update to select algorithm from list of available ones." ? Do we need to perform a manual selection ? If yes, how ? 

Thanks

**Comment by sseide** [comment]
regarding the crypto error - at first the algorithm "sha" was hard-coded, but node 11.x removed this one from the list of supported algorithms (or openssl lib used by node removed it).
Therefore i changed the code to use the first algorithm starting with "sha" to be used. This included multiple ones on Node 11.x too. No actions needed by users.
Code change see here https://github.com/sseide/redis-commander/commit/9cb939cb380e49276176b97382656a661adc18a3

But as i understand this one is not a problem anymore?
What is the console error message of your last try (adding manually via UI)? Or the message when trying to reestablish a save connection from config?

Connecting manually with redis console client works?
`redis-cli -s /home/user/Desktop...`

**Comment by Vincent-CIRCL** [comment]
Thanks for the explanation.

Sorry for the my unclear explanation. So : 

- `redis-commander --redis-socket ./(...)/cache.sock ` generates the same hash issue as previously discussed (still)
- `redis-commander --cc --redis-socket ./(...)/cache.sock ` does not generate any issue, nor any output. However, even if the UI is accessible, no redis data is displayed. See previous screenshots.
- `redis-cli -s ./(...)/cache.sock` does work. No problem. Data accessible.

**Comment by sseide** [comment]
ok, thanks.

all three ways use the same method where the hash algorithm is selected (connection data from config file (your first list entry), connection from command line (your second) or adding via web-ui).

it looks a bit strange that your system should not support any of the sha / sha256 / sha512 /... algorithms.

Can you please start `nodejs` interpreter interactive and enter the following command:
```console.log(require('crypto').getHashes())```
and send me the output with all algorithms supported?

**Comment by Vincent-CIRCL** [comment]
Of course ! :)

Here they are : 
`> console.log(require('crypto').getHashes())
[ 'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA3-224',
  'RSA-SHA3-256',
  'RSA-SHA3-384',
  'RSA-SHA3-512',
  'RSA-SHA384',
  'RSA-SHA512',
  'RSA-SHA512/224',
  'RSA-SHA512/256',
  'RSA-SM3',
  'blake2b512',
  'blake2s256',
  'id-rsassa-pkcs1-v1_5-with-sha3-224',
  'id-rsassa-pkcs1-v1_5-with-sha3-256',
  'id-rsassa-pkcs1-v1_5-with-sha3-384',
  'id-rsassa-pkcs1-v1_5-with-sha3-512',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5-sha1',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha3-224',
  'sha3-256',
  'sha3-384',
  'sha3-512',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512-224',
  'sha512-224WithRSAEncryption',
  'sha512-256',
  'sha512-256WithRSAEncryption',
  'sha512WithRSAEncryption',
  'shake128',
  'shake256',
  'sm3',
  'sm3WithRSAEncryption',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool' ]
`

**Comment by sseide** [comment]
yes - from this list "sha1" as first algorithm is selected and used.

Testing with new local vm (debian 9) and fresh install of nodejs 11.15.0 (latest 11.x from nodesource.com) i was able to connect to local socket without problem. Could retrieve and modify data...

```
$ bin/redis-commander.js --redis-socket /var/run/redis/redis.sock 
No Save: false
listening on  0.0.0.0 : 8081
Redis Connection /var/run/redis/redis.sock using Redis DB #0
loading keys by prefix ""
found 1 keys for ""
loading key "x" from "U:4253cb897fce89b3:0"
```

For tests please use code from github via git-clone of master branch. The last npm release is a bit behind and will be done over next days. The fix for the hash algorithm selection is not part of latest npm release (0.6.4), only part of master-branch right now.

The docker image is the same version as github master branch.

**Comment by sseide** [comment]
@Vincent-CIRCL is it working with latest version cloned from github? Or are there problems too?

**Comment by Vincent-CIRCL** [comment]
No .. I still have the problem. But as you already checked on your side, I may do something wrong.
I'll work without redis-commander for now, then :)
Thanks however for the help.

**Comment by sseide** [comment]
Last question then:  As you are using Manjaro linux - what version is it? or is there an vm image/vagrant box?
And whats the entire output of redis commander? Maybe there are some other hints in there...

**Comment by Vincent-CIRCL** [comment]
As It was written before : 
Node : v11.14.0
OS : 4.19.36-1-MANJARO

Full install, not a VM.
I also tried to change socket permission, no change.

**Comment by sseide** [comment]
Thanks.

Good news - hash algorithm selection works, no crash there anymore.
And Redis Commander was able to connect to two of the three dbs (`storage.sock` and `cache.sock` with full path).

As you started it with one socket only given at command line, the other two must be saved inside the config file (config/local-development.json probably) - cleaning up this file should help.

The socket from the cli you gave with `--redis-socket` works - it reported a successful connection to `DB #0`. And old saved one failed.

If you do not want redis commander to store connection data inside its config file use `--nosave` as param too, or `--cc` as you have done bevor (=deleting all custom config files)

**Comment by Vincent-CIRCL** [comment]
How nice is that. Big thanks ! That worked !

```
./bin/redis-commander.js -cc --redis-socket /home/user/Desktop/folder/Helpers/database_sockets/storage.sock
No Save: false
listening on  0.0.0.0 : 8081
Redis Connection /home/user/Desktop/folder/Helpers/database_sockets/storage.sock using Redis DB #0
loading keys by prefix ""
found 2 keys for ""
(...)
```

**Comment by sseide** [comment]
Lucky me - no new bug to fix :-)

**Comment by sseide** [comment]
New version 0.6.5 with bugfix released to NPM too.

Close this issue - feel free to reopen if this not working as expected.
