### ISSUE TITLE
redis-commander not found on mac os

### ISSUE THREAD

**Issue by RazmikMkrtchyan** [joeferner/redis-commander#273]
I am using npm v6.1.0,node v10.4.1. And npm install -g redis-commander works properly,but after it $ redis-commander brings redis-commander: command not found

**Comment by sseide** [comment]
NPM installable version is really old by now with known problems. Please either checkout latest from github or use docker image.

**Comment by sseide** [comment]
I know its a bit late - but did you called `npm link` after installing via npm install?
The "link" is needed to create the executables inside the PATH variable...

**Comment by RazmikMkrtchyan** [comment]
> I know its a bit late - but did you called `npm link` after installing via npm install?
> The "link" is needed to create the executables inside the PATH variable...

Thank you,it works for me.
