### ISSUE TITLE
Error `/bin/sh: apk: not found` in Docker image

### ISSUE THREAD

**Issue by ebreton** [joeferner/redis-commander#279]
Hello, 

**Description of the bug:** When trying to execute the command `RUN  apk --no-cache add bind-tools` in a docker image FROM the redis-container one, the exception `/bin/sh: apk: not found` is raised

**Result expected:** the the apk command executes correctly and bind-tools is installed

## Steps to reproduce

- Write the following Dockerfile: 
```
FROM rediscommander/redis-commander

RUN  apk --no-cache add bind-tools
```

- Run the build command
```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM rediscommander/redis-commander
 ---> a45adc980a54
Step 2/2 : RUN  apk --no-cache add bind-tools
 ---> Running in c322effff4b2
/bin/sh: apk: not found
The command '/bin/sh -c apk --no-cache add bind-tools' returned a non-zero code: 127
```

## More information:

The command runs properly on the docker image `node:8-alpine`, FROM which the redis-commander image inherits
```
$ docker run --rm node:8-alpine which apk
/sbin/apk
$ docker run --rm rediscommander/redis-commander which apk

$
```

**Comment by sseide** [comment]
Do you build the redis-commander image from latest github sources for yourself? Or use docker-hub version?

Most of the system tools are removed during hardening step to decrease attack surface running this container. I will create an fix to allow apk running if needed...

Right niow you can do this: build redis-commander base image for yourself and remove call to "harden.sh" from first build, just call this at the end of your own image build process

**Comment by sseide** [comment]
Will work again with this PR. But calling "apk update" before is needed.

```
FROM rediscommander/redis-commander

RUN  apk update \
          apk --no-cache add bind-tools
``` 
As apk stores many cache files not needed while running the container, you should consider removing all this temporary files at the end of your RUN command too to not add them to the image layer. Just look inside  redis-commander Dockerfile  for the commands needed.

**Comment by ebreton** [comment]
Thanks a lot @sseide !!! 🥇 

It is exactly what I needed, and I can move to next step. Many thanks for the complementary advices and recommendation on the cleaning part 👍 

Emmanuel
