### ISSUE TITLE
input the correct username and password, but pupup login form every time

### ISSUE THREAD

**Issue by qdlake** [joeferner/redis-commander#288]
If i set HTTP_USER and HTTP_PASSWORD, then input the correct username and password, but pupup login form every time. 

ps: set HTTP_PASSWORD_FILE, still not logged in。

docker-compose.yml:
---
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    networks:
      - back-net
    ports:
      - "16379:8081"
    secrets:
      - redis_commander
    environment:
      - HTTP_USER=${DB_USER}
      - HTTP_PASSWORD_FILE=/run/secrets/redis_commander
      - REDIS_HOSTS=redis-cluster:redis-cluster:7000,redis-cluster:redis-cluster:7001,redis-cluster:redis-cluster:7002,redis-cluster:redis-cluster:7003,redis-cluster:redis-cluster:7004,redis-cluster:redis-cluster:7005

**Comment by sseide** [comment]
How do you installed redis-commander? github? npm?

**Comment by qdlake** [comment]
use docker.  docker image is rediscommander/redis-commander:latest.

**Comment by sseide** [comment]
related to #290 ? Cannot reproduce. Test with HTTP_PASSWORD_FILE worked too. Do you two have something in common at your browser (settings)?

**Comment by sseide** [comment]
found something with windows based browsers - seem to behave a little bit different. Can you please retry with latest docker image?

**Comment by sseide** [comment]
Is this issue resolved or still exists with latest version? Can this ticket be closed?

**Comment by sseide** [comment]
Closed due to missing feedback. If Problem exists with latest version feel free to reopen with additional informations.
