### ISSUE TITLE
Using `[` in a key causes failures for some commands.

### ISSUE THREAD

**Issue by rquadling** [joeferner/redis-commander#295]
I use PHP with Doctrine Cache and that uses `[` and `]` to segment aspects of the key (`namespace[key][version]`).

As a consequence, redis-commander fails to operate on these appropriately as some redis commands require `[` to be escaped if they are part of the key and not part of the command's regex syntax.

I'm happy to provide more details if needed on this.

**Comment by sseide** [comment]
did you tried to use redis scan command instead of keys? start app with "--use-scan" to test. Maybe that will help (but dont know)...

**Comment by rquadling** [comment]
```
$ npm install redis-commander --force --global
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
/usr/local/bin/redis-commander -> /usr/local/lib/node_modules/redis-commander/bin/redis-commander.js
+ redis-commander@0.4.5
updated 1 package in 10.771s

$ redis-commander --help
Options:
  --redis-port                    The port to find redis on.              [string]
  --sentinel-port                 The port to find sentinel on.           [string]
  --redis-host                    The host to find redis on.              [string]
  --sentinel-host                 The host to find sentinel on.           [string]
  --redis-socket                  The unix-socket to find redis on.       [string]
  --redis-password                The redis password.                     [string]
  --redis-db                      The redis database.                     [string]
  --http-auth-username, --http-u  The http authorisation username.        [string]
  --http-auth-password, --http-p  The http authorisation password.        [string]
  --address, -a                   The address to run the server on.       [string]  [default: "0.0.0.0"]
  --port, -p                      The port to run the server on.          [string]  [default: 8081]
  --nosave, --ns                  Do not save new connections to config.  [boolean]  [default: true]
  --save, -s                      Save new connections to config.         [boolean]
  --noload, --nl                  Do not load connections from config.    [boolean]
  --clear-config, --cc            clear configuration file              
  --root-pattern, --rp            default root pattern for redis keys     [default: "*"]

$ redis-commander --use-scan
No Save: true
listening on  0.0.0.0 : 8081
Redis Connection redis:6379 Using Redis DB #0
loading keys by prefix ""
found 1 keys for ""
loading keys by prefix "[THEME"
found 0 keys for "[THEME"
loading key "[THEME" from "redis:6379:0"
```

No change, and also no `--use-scan` option when starting redis-commander.

I can see the README.md for this project mentions that setting, but it doesn't seem to be present in the release I have (0.4.5) which is also the latest release on this project.

**Comment by sseide** [comment]
do not use npm - this version is old with lots of known bugs.
Either install from github directly or use docker container.

**Comment by rquadling** [comment]
Github release is still 0.4.5? Are you saying use the dev version?

OOI, running `keys *` in redis-commander outputs:

```
keys *
1) [THEME:244:frontend:1539604223][1]
```
which is what Doctrine Cache creates.

**Comment by sseide** [comment]
The maintainer - Joe Ferner - just did not created new releases or updated the version number (github and npm) for some time. But lot of things changed and got improved and security bugs fixed within master branch since then. You do not want use the npm version...

**Comment by rquadling** [comment]
OK.

Got docker container running with the same issue.

How do I pass `--use-scan` to the docker container. I'm using docker-compose.

**Comment by rquadling** [comment]
I think https://github.com/joeferner/redis-commander/blob/master/docker/entrypoint.sh needs to be updated to support an envvar `USE_SCAN` -> `--use-scan`.

**Comment by rquadling** [comment]
https://github.com/joeferner/redis-commander/pull/297

**Comment by rquadling** [comment]
As some of the `--options` are envvars, I thought making this one an envvar would help with consistency and mean no need to override the command and possibly break things if the command changes.

**Comment by rquadling** [comment]
Hmmm. Still doesn't work

```
$ docker-compose logs -f redis-commander 
Attaching to redis-commander
redis-commander    | Creating custom redis-commander config.
redis-commander    | Configuration:
redis-commander    |     {
redis-commander    |     "sidebarWidth":250,
redis-commander    |     "locked":false,
redis-commander    |     "CLIHeight":50,
redis-commander    |     "CLIOpen":false,
redis-commander    |     "default_connections": [
redis-commander    |         {
redis-commander    |             "label":"local",
redis-commander    |             "host":"redis",
redis-commander    |             "port":"6379",
redis-commander    |             "password":"",
redis-commander    |             "dbIndex":0
redis-commander    |         }
redis-commander    |         ]
redis-commander    |     }
redis-commander    | node ./bin/redis-commander --use-scan
redis-commander    | Using scan instead of keys
redis-commander    | No Save: false
redis-commander    | listening on  0.0.0.0 : 8081
redis-commander    | Redis Connection redis:6379 Using Redis DB #0
redis-commander    | loading keys by prefix ""
redis-commander    | scanning: 0: 2
redis-commander    | found 2 keys for ""
redis-commander    | loading keys by prefix "[THEME"
redis-commander    | scanning: 0: 0
redis-commander    | found 0 keys for "[THEME"
redis-commander    | loading key "[THEME" from "redis:6379:0"
redis-commander    | loading keys by prefix "PHPREDIS_SESSION"
redis-commander    | scanning: 0: 1
redis-commander    | found 1 keys for "PHPREDIS_SESSION"
redis-commander    | loading key "PHPREDIS_SESSION:s8uub58l4occ41g3otuao55nr0" from "redis:6379:0"
redis-commander    | loading key "[THEME" from "redis:6379:0"
```

From redis-commander's prompt.
```
keys *
1) PHPREDIS_SESSION:s8uub58l4occ41g3otuao55nr0
2) [THEME:244:frontend:1539604223][1]
```

**Comment by rquadling** [comment]
Interestingly, I changed the `--folding-char` to `!` and things worked (just without the folding/nesting).

So maybe this is a folding issue rather than a `[` issue?

**Comment by sseide** [comment]
mmh - maybe . Than it could be either client side or server-side. Does the browser console or docker logs say something of interest?

btw: your two redis keys from your comment - first one (PHPREDIS_SESSION) could be split on ":" as folding char. But second one does not has anything at all to split at (or at least have not testet if multi-char works too with "]["... But "[" and "]" are special on redis "keys" command (https://redis.io/commands/keys)

**Comment by sseide** [comment]
With your last log using scan:
```
found 2 keys for ""
redis-commander    | loading keys by prefix "[THEME"
redis-commander    | scanning: 0: 0
redis-commander    | found 0 keys for "[THEME"
```

Seems to indicate there is a problem server-side on checking for this "virtual" folders. Server does not found any keys starting with `[THEME`

**Comment by sseide** [comment]
I believe issue is here:

https://github.com/joeferner/redis-commander/blob/db5f61fb465c0d6b528f70a3b13047d2db74594e/lib/routes/apiv1.js#L673-L686

A string is constructed to be used as pattern for the redis `KEYS` command, but this command does not return anything. Caused by `[` being a special pattern for `KEYS` command (as referenced in doc above)

**Comment by sseide** [comment]
beside `*` `[`, `]` and `?` should be quoted too inside prefix (line 676) i believe...

**Comment by rquadling** [comment]
PHP Sessions -> via redis are `PHP_SESSION:id` - these don't use Doctrine Cache.
Doctrine Cache is the one that uses `namespace[key][version]`. We construct the `key` part ourselves, so we can put there whatever we want. As Doctrine Cache builds keys for all different sort of caching systems, that format is pretty much baked in at a very low level and not easily got around. So until they do, I'm stuck with the format.

Ideally a `STRIP_CHARS`, `REPLACE_CHARS` and/or `FOLDING_CHARS` (all plural) would work for me. I can then remove the `[` and `]` and everything should work just fine. Maybe a `Doctrine` mode?

**Comment by sseide** [comment]
Have no idea about PHP/Doctrine. But creaetd PR to at least display the doctrine entries and to be able to navigate and edit all keys...

Now, using `:` as folding char: it will display your key `[THEME:244:frontend:1539604223][1]`
```
|-- [THEME/*
    |-- 244/*
        |-- frontend/*
            |-- 1539604223][1]
```
Hope it helps. You can check when PR is merged, Docker images are build automatically afterwards...

**Comment by sseide** [comment]
Can this one closed? Or are there some other problems with doctrine?

**Comment by rquadling** [comment]
Happy to close.
