### ISSUE TITLE
Can support mult-language?

### ISSUE THREAD

**Issue by JIJL** [joeferner/redis-commander#299]
when i search for key，I got the garbled value，like this 
`��srjava.util.ArrayListx����a�Isizexpwsrjava.util.HashMap���`�F`

**Comment by sseide** [comment]
Seems to be binary data stored inside redis. There is no special handling right now for binary data, therefor no workaround available.

duplicate of #140

If its no binary data (check with redis-cli or similiar) please reopen issue with some more informations about the data stored inside redis.
