### ISSUE TITLE
Enhance OpenShift support

### ISSUE THREAD

**Issue by klmcwhirter** [joeferner/redis-commander#311]
The current version fails to start in OpenShift versions 3.9 and 3.11.

This is happening because the Docker deployment pieces do not meet the OpenShift requirements.

I am creating this issue to track discussion of the work I am doing on a fork of this repo.

Proposal:
* do not attempt refactor of existing Docker deployment mechanisms. There are use cases that depend on what is being done there - e.g., docker-compose
* utilize a stock OpenShift S2I image builder instead to build from source
* honoring the open-closed principle add pieces needed to allow the S2I image builder to build from source

See https://github.com/klmcwhirter/redis-commander for the repo fork location.

**Comment by sseide** [comment]
https://github.com/joeferner/redis-commander/issues/267#issuecomment-441110930

For basic support with current image only root owned home directory should be needed,
Numeric USER id may be helpfull...

**Comment by klmcwhirter** [comment]
I found a non-intrusive way to provide OpenShift support.

See PR #312
