### ISSUE TITLE
Error with request "browserify.js" in the latest version

### ISSUE THREAD

**Issue by rpindado** [joeferner/redis-commander#314]
The CLI doesn't work, and I just noticed this in the browser:

![image](https://user-images.githubusercontent.com/5924074/49141464-ee60d480-f2f6-11e8-94dd-e545c1a3c7d1.png)

It was working without any problems a few days ago

**Comment by sseide** [comment]
Where do you run redis-commander? Are you running it under Windows?
Which version of Redis-commander?

Works under Linux and inside Kubernetes without problem for us...

**Comment by sseide** [comment]
Thanks - strange ist working for me under linux with docker - What kind of browser? And can you please provide the logs from redis-commander server?

Maybe related to #232

**Comment by rpindado** [comment]
`/usr/local/lib/node_modules/redis-commander # redis-commander
No Save: false
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:8081
    at Server.setupListenHandle [as _listen2] (net.js:1294:14)
    at listenInCluster (net.js:1342:12)
    at doListen (net.js:1480:7)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1321:8)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)`

Tested in Chrome, Firefox, Opera and Edge, same behaviour in all of them

**Comment by sseide** [comment]
can u check with latest version again (github source or docker)? There is a fix incorporated that did helped others but was remove for some reason...

**Comment by sseide** [comment]
Can this be closed or is there some issue left?

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
