### ISSUE TITLE
Use in an existing express app

### ISSUE THREAD

**Issue by cesarvarela** [joeferner/redis-commander#321]
Hi, Is it possible to use this with an existing express app? Like mounting it in a specific route.

**Comment by sseide** [comment]
dont think so (but dont know), but with pr #330 it should be a lot easier to include redis commander as a standalone web-server running on its own port as a second express app. setup is much easier now, just give app.js a list of redis connections and start it (check end of `bin/redis-commander.js` file around startWebApp() if interested...

 (disclaimer - not really tested to include into other app, just from reading code)

**Comment by sseide** [comment]
Will close this one. If there are further questions or things to change to get it working feel free to reopen issue...
