### ISSUE TITLE
how to allow multiple REDIS_HOSTS?

### ISSUE THREAD

**Issue by babatundebusari** [joeferner/redis-commander#328]
How can one target multiple redis hosts with the `REDIS_HOSTS` environment variable?

I will like to create a drop down where i can select the `REDIS_HOST` and connect to it from the GUI
at the moment i can only add one redis hosts and not able to specify multiple hosts

**Comment by sseide** [comment]
REDIS_HOSTS for docker container is a comma separated list of hosts with the connection info per host as describe in the readme. just give all hosts needed as follows (3 redis here):

```
local:127.0.0.1:6379:0,remote1:20.2.2.2,remote2:20.3.3.3:6379:2:mysecretpass
```
Then you will see all three servers on the left side inside the tree view.

**Comment by babatundebusari** [comment]
well redis commander does not work with multiple hosts from environment variable

**Comment by sseide** [comment]
well we are using it with multiple redis hosts inside REDIS_HOSTS env var. Therefor its working as i said...

Maybe a little bit more informations how you installed it and how exaclty do you start redis commander?

**Comment by sseide** [comment]
The ip address or dns name of the redis server host is needed. If rdis server is running locally you must either say `localhost` or `127.0.0.1`. The `Name/Label` can be choosen as you like, its only for display.

your example given would translate to the following connections:

| Name/Label | IP-Address/DNS-Name | Port | Redis-Database | Password |
| --- | --- | --- | --- | ---|
| local | remote1 | 6379 | 0 | |
| local | remote2 | 6379 | 0 | |
| local | remote3 | 6379 | 0 | |

Therfore you will connect to three different servers with the hostnames `remote1`, `remote2` and `remote3`on standard port to the default database `0` without authentication. All three would use the same name for display (not a good idea).

My example translates to the following three connections (one on local server, two on remote servers)
```local:127.0.0.1:6379:0,remote1:20.2.2.2,remote2:20.3.3.3:6379:2:mysecretpass```

| Name/Label | IP-Address/DNS-Name | Port | Redis-Database | Password |
| --- | --- | --- | --- | ---|
| local | 127.0.0.1 | 6379 | 0 | | 
| remote1 | 20.2.2.2| 6379 | 0 | |
| remote2 | 20.3.3.3 | 6379 | 2 | mysecretpass |

**Comment by babatundebusari** [comment]
the remote hosts are all local on the same docker host and the redis commander can find the remote container by the name `remote``, `remote2` etc

so what is best way to set it up then?

remote1 container is running on network remote1
remote2 container is running on network remote2

redis commander is running on another network and can connect to remote1 and remote2

**Comment by sseide** [comment]
Seems to be more of a docker problem. Your question is how are the "real" names of the docker hosts runnning the redis servers seen from inside the redis commander container. If you do not know the ip addresses and host names are not resolvable via dns you may need to add these dns names to the `docker run` command of redis commander to let docker add the names to the /etc/hosts file (https://blog.codeship.com/using-the-add-host-flag-for-dns-mapping-within-docker-containers/). 

You can connect to the docker container running redis commander (via `docker exec`) to check the dns server used and all entries of the `/etc/hosts` file, maybe the informations you need is already there...

The REDIS_HOSTS env var must contain either the ip addresses of the redis server or the dns name to be able to resolve to an ip address...

**Comment by babatundebusari** [comment]
The dns names are resolvable i did not say they are not resolvable
i mean using ip address of docker containers defeats the whole purpose of using docker

if i only specified one host, it works but when i tried to add multiple then it does not work

**Comment by sseide** [comment]
thats where hostnames com into play. IF all name "remote1", "remote2", "remote3" can be resolved inside the docker image than it will connect to all three servers.

Please log into the redis-commander container and do an `ls -la /redis-commander/config/`. There will be a file named `local-production.json` (or similiar if you did set `NODE_ENV` env var). The content of this file contains all connection informations parsed from your `REDIS_HOSTS` env var inside "connections" list. Check these and than try to ping all "host" names. Than you will see if the are reachable from inside the container.

The file should look something like:
```
{
    "connections": [
        {
            "label":"local",
            "host":"remote1",
            "port":"6379",
            "password":"",
            "dbIndex":0
        },
        {
            "label":"local",
            "host":"remote2",
            "port":"6379",
            "password":"",
            "dbIndex":0
        },
        {
            "label":"local",
            "host":"remote3",
            "port":"6379",
            "password":"",
            "dbIndex":0
        }
      ]
    }
```

side note: if not done recently please delete your redis commander docker image and let it pull the most recent one as this contains some fixes.

**Comment by babatundebusari** [comment]
you keep not answering my question directly

is this correct?

`local:remote1:6379,local:remote2:6379,local:remote3:6379`

**Comment by sseide** [comment]
Because it is not possible to answer this question with the data you have given - i cannot say if they are "correct" or "not" without having your docker setup. I can only say what servers it tries to reach with this REDIS_HOSTS var.

And as I said, if the hostnames "remote1", "remote2" and "remote3" are resolvable you will get three entries in the tree of the left side of the ui, each one representing one of the servers.

**Comment by babatundebusari** [comment]
just checked and it worked!

`local:remote1:6379,local:remote2:6379,local:remote3:6379`

Thanks for your help!!!
