### ISSUE TITLE
Empty Key List

### ISSUE THREAD

**Issue by jamiejackson** [joeferner/redis-commander#332]
I'm using the `rediscommander/redis-commander:latest` docker image, and my production stack shows a blank left panel (where keys are usually displayed). Export does export expected data, but the GUI is empty:

![image](https://user-images.githubusercontent.com/479475/50796619-2406bf00-12a0-11e9-8808-87a123729cc9.png)

Here's a well-behaved redis-commander from another stack:

![image](https://user-images.githubusercontent.com/479475/50796643-3da80680-12a0-11e9-9dd0-3cc36ab14bb5.png)

Any idea what's going on or how to fix it?

**Comment by sseide** [comment]
Are there some errors inside redis commander server logs or browser console?

**Comment by ajays28** [comment]
There are no errors inside Redis commander browser console. 
Log file size is increasing. Yesterday it was 55MB, today it's 62MB.

Here are the few lines:
kcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4wSXEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+GiRxAH4aJHEAfhokcQB+

**Comment by sseide** [comment]
looking at your pictures again - the one not working has TWO redis instances configured, Do you really have a redis server running at localhost? If not - this was a bug introduced by a commit some days ago..

please delete the docker image of redis commander and rerun it.

**Comment by ajays28** [comment]
ok, we'll try.
I opened FireFox "HTTP Header Live" and monitoring the traffic, FireFox is refreshing the page every 20 seconds and after sixth refresh I see "NS_ERROR_NET_RESET"

**Comment by ajays28** [comment]
Deleted the docker image of Redis commander and re-ran the build. Commander has only one instance and we can see all the keys!
Thank you

**Comment by sseide** [comment]
your welcome - can this issue be closed?
