### ISSUE TITLE
renderEjs not defined

### ISSUE THREAD

**Issue by tcees** [joeferner/redis-commander#336]
Hi, 

I've just installed redis-commander@0.6.2. After logon, I get the following errors in my browser:

redisCommander.js:768 Uncaught SyntaxError: Unexpected token {
(index):215 Uncaught ReferenceError: renderEjs is not defined
    at Object.success ((index):215)
    at i (jquery-2.2.4.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.js:2)
    at z (jquery-2.2.4.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.js:4)

**Comment by sseide** [comment]
was problem with newer Chrome (and IE), fixed at CR #334 - but this was added after release of 0.6.2.

Workaround: use Docker image or github sources until new version is released.

**Comment by sseide** [comment]
Or use Firefox....

**Comment by sseide** [comment]
Version with bugfix released to npm too (0.6.3)
