### ISSUE TITLE
Cannot add new key

### ISSUE THREAD

**Issue by kpsledge** [joeferner/redis-commander#338]
When using the button for adding a new key, it never assigns the key correctly.  The key either comes across as a blank key, or "undefined", but the value is set correctly.  Any ideas?  

Ubuntu 18.04, NodeJS 8.15.0, used npm to install.

**Comment by sseide** [comment]
already fixed in Github and Docker image. But not released to npm right now.
commit 37d7a2b14063b14d56e47b388b100bfddc60caa8

Or use Firefox and not Chrome-based browser as long as no npm update is available (afair)...

**Comment by kpsledge** [comment]
so can I just copy the redisCommand.js file in to my server from Github? If so, are there other files I need to grab?

Sorry for the newbie questions, I'm not a NodeJS developer.

**Comment by kpsledge** [comment]
Awesome! Thanks for the help, it's working correctly now.

**Comment by sseide** [comment]
Version with this bugfixes got released to npm (v0.6.3) too.
