### ISSUE TITLE
Read-Only Connection

### ISSUE THREAD

**Issue by nsankaranarayanan** [joeferner/redis-commander#341]
I understand that there is some level of authentication provided.
Is there a way to allow users to have a read-only view? Basically they can see the keys and values but cannot change or delete them.

**Comment by sseide** [comment]
read-only mode is currently not available. I thought about it but do not know when i'm able to implement it.. Feel free to start a PR.

And for authentication there is only one user by now. Therefore basic read-only mode whould mean the entire app would run in read-only mode. For read-write access a second one at another port could be started...

**Comment by wwild** [comment]
I think having a general read only mode, that basically makes the one user read only, would be a good first step.
Basically it allows the redis server to be used as a monitoring / persistence store, by only having the corresponding process add data and giving everybody else read only access

+1 from me

**Comment by sseide** [comment]
Hi, i updated redis-commander to allow starting in read-only mode. It would be nice if someone could give it a try and check if its working as expected or if i missed something...

Currently only in git branch read-only-mode, no Docker images. Thought some more test might be good before merging...

Feedback welcome!

**Comment by wwild** [comment]
@sseide Thanks alot for the change.

I tested it very rudimentary and it works fine.
I tried a few minutes to get around the read only mode and had no success, but it wasn't an extensive test.

Might have the time later to do a comprehensive test, but can't promise anything..

**Comment by sseide** [comment]
Found a bug in read-only checks, pushed a fix, therefor please update before doing further tests.

**Comment by sseide** [comment]
merged it into master, docker image with read-only support will show up soon...

**Comment by sseide** [comment]
This version got release to npm too (0.6.3). If you find some bugs with it, please create a new issue for that.

Thanks.
