### ISSUE TITLE
Can't display empty folder names (two or more consecutive folding chars)

### ISSUE THREAD

**Issue by braiamdev** [joeferner/redis-commander#342]
Redis server: 5.0.3
Redis-commander: 0.6.2, 0.6.3-rc2

```
redis> hset main::sub key value
```

Redis commander displays a folder instead of a hash editor

**Comment by sseide** [comment]
please change folding char from default `:` to something else. Can be done via command line param, env variable or config file.

The folding char (default is `:`) is use to create some virtual hierarchy and sort keys into "folder" in the tree view. Having double `::` will create an folder without name, that cannot be displayed...

**Comment by braiamdev** [comment]
@sseide Changing the folding char worked for me. Would not being able to display empty folder names still be an issue? or should I close this issue? Thanks for your help!

**Comment by sseide** [comment]
Good to hear that changing the folding char works.

And yes - its a bug nobody hit until now. Please leave it open. If you have time for a fix its welcome.

**Comment by sseide** [comment]
New version 0.6.5 with bugfix released to NPM too.

Close this issue - feel free to reopen if this not working as expected.
