### ISSUE TITLE
esj not defined and $.jstree is undefined

### ISSUE THREAD

**Issue by pikax** [joeferner/redis-commander#344]
- chrome **72.0.3626.121** 
- redis-commander@0.6.4
- yarn@1.13.0
- node@10.15.2
- Windows 10

When I connect to localhost I can't get any keys and the console shows errors:

![image](https://user-images.githubusercontent.com/4620458/54185180-497e9780-44a0-11e9-8c96-c6612a187809.png)

the cli don't show any error:
![image](https://user-images.githubusercontent.com/4620458/54185306-92cee700-44a0-11e9-8df7-4864fbd5a77f.png)

![image](https://user-images.githubusercontent.com/4620458/54185335-ad08c500-44a0-11e9-8877-4a26baedde4a.png)

**Comment by sseide** [comment]
How do you installed it?

And there are some more errors missing from the browser console - there seem to be a lot of HTTP 404 before? Please post all errors from console.

**Comment by pikax** [comment]
using `yarn global add redis-commander` 
![image](https://user-images.githubusercontent.com/4620458/54189233-450aac80-44a9-11e9-93d5-a40ee824b83f.png)

**Comment by sseide** [comment]
As Redis Commander cannot load jstree.js file this var cannot be defined...

`yarn global` seems to install packages in unexpected places.
Can you please check the following?
Inside redis commander installation directory (where redis commander package.json is) there shall be the following directories:
* `node_modules/jstree/dist/`
* `node_modules/clipboard/dist` etc.

if not - can you please check where yarn installed the `jstree` and `clipboard` modules?

as a short fix, uninstalling app with yarn and reinstall with `npm -g install redis-commander` should work.

**Comment by pikax** [comment]
redis-commander folder:
![image](https://user-images.githubusercontent.com/4620458/54195428-89507980-44b6-11e9-96b6-31869e01d96c.png)


```
XX@XX-XX C:\Users\XX\AppData\Local\Yarn\Data\global
> yarn why jstree
yarn why v1.13.0
[1/4] Why do we have the module "jstree"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "jstree@3.3.7"
info Reasons this module exists
   - "redis-commander" depends on it
   - Hoisted from "redis-commander#jstree"
Done in 1.05s.

XX@XX C:\Users\XX\AppData\Local\Yarn\Data\global
> yarn why clipboard
yarn why v1.13.0
[1/4] Why do we have the module "clipboard"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "clipboard@2.0.4"
info Reasons this module exists
   - "redis-commander" depends on it
   - Hoisted from "redis-commander#clipboard"
   - Hoisted from "@vue#cli#@vue#cli-ui#prismjs#clipboard"
Done in 1.25s.
```

the modules `jstree` and `clipboard` are found in `C:\Users\XX\AppData\Local\Yarn\Data\global\node_modules` same folder as redis-commander

**Comment by pikax** [comment]
I think the issue can be found here: 
https://github.com/joeferner/redis-commander/blob/master/lib/app.js#L84

**Comment by sseide** [comment]
ok - but redis commander is searching them inside its own local `node_modules` folder... 
Files not there -> HTTP 404 -> Boom.

Can only be fixed converting project to webpack or similiar in the long run...
Dos installing via npm helps?

**Comment by sseide** [comment]
yes. working that way with npm, git checkout or inside docker ..

**Comment by pikax** [comment]
with npm it works, might be useful to add to the readme that yarn is not supported

**Comment by sseide** [comment]
Yes, will add it. Maybe only problem with `yarn global`? Local yarn working?

**Comment by pikax** [comment]
same error using `yarn add redis-commander`, because yarn flats all dependencies in the `{root}/node_modules` 
Npm in the other hand it nests the dependencies

**Comment by sseide** [comment]
thanks for testing - added note to the readme

**Comment by sseide** [comment]
does it work now? can ticket be closed?

**Comment by pikax** [comment]
Yes runs on NPM

**Comment by jaafarassaf** [comment]
Hello I am having the same issue, even if I am using npm

Any thought how I could fix that ? Thank you

![2020-02-13 16_20_51-redis-cli](https://user-images.githubusercontent.com/48514858/74449415-d6825b80-4e7c-11ea-8cfa-bf30b36d18e8.png)

**Comment by sseide** [comment]
What OS do you use? Whats your node version? Are there any log messages server-side which may help here? Currently i do not have any idea...

The first two lines i suspect to be HTTP404 too, therefore mime-type is text/html. So its the same as all errors below.

**Comment by jaafarassaf** [comment]
@sseide Thank you for your response, I actually managed to solve this based on another recent ticket. I am using windows and there was a problem with regexp due to the backslashes. 

Thank you very much
