### ISSUE TITLE
exec format error in docker for arm64

### ISSUE THREAD

**Issue by schwab** [joeferner/redis-commander#345]
Upon clean install of redis commander on docker 18.09.x for linux/arm64, rediscommander immediately fails with "exec forma error".  

Is it possible to run rediscommander on an arm64 architecture?  Perhaps with an env flag or something?

Thanks

**Comment by sseide** [comment]
Dockerhub does not provide multi plattform images for Redis Commander right now - only for amd64. Therefore you have to build the arm64 image for yourself.

Self build image should be working then... but i did only a short test on RasPi with debian/armhf.

btw - if you know a service to auto-build images for other architectures than amd64 or do it right at docker hub auto-build service i would be interessted to hear...

**Comment by miguelchico** [comment]
I just tested it and you can build an image just replacing node:8-alpine by arm32v7/node:8-alpine and it works perfectly

**Comment by sseide** [comment]
With the new base image of `alpine:3.11` (startting from version 0.7.0) it should work out-of-the-box as this image is available for `arm` and `arm64` too.

**Comment by npjonath** [comment]
I temporary push a public image on docker hub awaiting official release for arm.
npjonath/redis-commander:v0.7.1

**Comment by sseide** [comment]
finally multi-arch images available and automatically build via github action.
Currently published to GitHub Container Registry only but will try to reenable Dockerhub too.

https://github.com/joeferner/redis-commander/pkgs/container/redis-commander
