### ISSUE TITLE
config key "connections.0.port" has invalid value (current: true). key must be number!

### ISSUE THREAD

**Issue by quogourav** [joeferner/redis-commander#346]
Getting error on running redis-commander

**config key "connections.0.port" has invalid value (current: true). key must be number!**

**Comment by sseide** [comment]
as this error message states you started redis commander with an invalid config. Your first connection definition (index 0) is invalid.

Please check config files, environemnt vars or your command line. When using network connection the redis server port MUST be a valid port number or not set at all (using default port 6379 then)

**Comment by sseide** [comment]
closed a there are now more activity
