### ISSUE TITLE
Add support remoteAddress - real IP header

### ISSUE THREAD

**Issue by Grokon** [joeferner/redis-commander#348]
Hello, please add support for real IP header from proxy in logs (remote-addr', req.headers['x-forwarded-for'])
I'll try proxing from nginx to redis-commander and see only:
`redis-commander    | Login success for user admin from remote ip 127.0.0.1
redis-commander    | Login success for user admin from remote ip 127.0.0.1
`

**Comment by sseide** [comment]
New version (github or docker image) does support this, e.g:
* cli param "--trust-proxy 1"
* setting env var "TRUST_PROXY=1"
* config file key "server.trustProxy"

Either set this value to a boolean-like value (1, true) or to a string with ip addresses of proxies to trust and not use as remote ip addresses. For more information of possible values please check the Node Express documentation at https://expressjs.com/en/guide/behind-proxies.html

**Comment by Grokon** [comment]
thanx, now it's work.
