### ISSUE TITLE
Copying/Pasting large keys in redis-commander

### ISSUE THREAD

**Issue by harryjoshi** [joeferner/redis-commander#352]
Hello
Im using Redis Commaner to manage spreadsheets built in ethercalc (https://github.com/audreyt/ethercalc). Even with an empty spreadsheet, ethercalc generates a large key stored in redis. I'm trying to copy/paste keys and edit contents via Redis commander, however it appears the max upload size is 100k. Is there a way to increase this to 1024k? 
Previous versions did not have this limitation. Thank you!!

**Comment by sseide** [comment]
its the default value of the body-parser middleware used (see http://expressjs.com/en/resources/middleware/body-parser.html - at "limit"). Nothing we set explicit. So it must have change there at some time...

Cannot be set via config/env-var right now, must be done programmatically in app.js here...
https://github.com/joeferner/redis-commander/blob/318231440e0538edc54c0873b405ebef0876b0e1/lib/app.js#L138-L139

But should probably be configurable to allow special uses with larger bodys...

**Comment by sseide** [comment]
did it work with setting env var or config key?

**Comment by sseide** [comment]
New version 0.6.5 with fix released to NPM too.

Close this issue - feel free to reopen if this not working as expected.
