### ISSUE TITLE
Non blocking issue during installation on windows

### ISSUE THREAD

**Issue by ssougnez** [joeferner/redis-commander#356]
Hello,

I'm trying to install redis-commander on the following system:

* Windows 10
* Node v12
* Python 3.7.3

And when I run `npm install -g redis-commander`, I have the following issue (although, redis-commander is correctly installed and seems to work perfectly):

> C:\Users\SOUSE\AppData\Roaming\npm\redis-commander -> C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js
> 
> > bcrypt@3.0.6 install C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(400): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-win32-x64-unknown.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\SOUSE\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\SOUSE\\AppData\\Roaming\\npm\\node_modules\\redis-commander\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\SOUSE\\AppData\\Roaming\\npm\\node_modules\\redis-commander\\node_modules\\bcrypt\\lib\\binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt
> gyp ERR! node -v v12.3.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> node-pre-gyp ERR! System Windows_NT 10.0.17763
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SOUSE\\AppData\\Roaming\\npm\\node_modules\\redis-commander\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt
> node-pre-gyp ERR! node -v v12.3.1
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\SOUSE\AppData\Roaming\npm\node_modules\redis-commander\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\redis-commander\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 (node_modules\redis-commander\node_modules\bcrypt):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> + redis-commander@0.6.5
> updated 1 package in 40.366s

From what I see, the issue comes from the fact that https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-win32-x64-unknown.tar.gz does not exist.

Cheers

**Comment by sseide** [comment]
Thanks for the report. Its known that "bcrypt" is not compiling within a lot of different environments.
Thats the reason its an optional dependency only. During runtime its checked if this is available with automatic fallback to "bcryptjs" (pure JS but slower).

Best regards,

**Comment by ssougnez** [comment]
If I may, I don't know if it's possible, but it would be nice to state more clearly to the user that the installation didn't actually fail.

Indeed, I try reinstalling the package twice before noticing that it actually installed correctly the first time. I suspect that some people could think that the package just did not install properly and look for an alternative.

Cheers ;-)

**Comment by sseide** [comment]
yes, you have a point. Be here we are at cross-plattform territory ;-)

As you are running Windows - may i ask you to add the following snippet to the end of your `package.json` and rerun `npm install`? Just to see if this works inside Windows command shell too:

```
  "scripts": {
    "postinstall": "node -e 'console.log(\"\\n==> INFO: Errors with module \\\"bcrypt\\\" can be ignored\\n\\n\")'"
  }
```

Another variant may be:

```
  "scripts": {
    "postinstall": "echo '==> INFO: Errors with module \"bcrypt\" can be ignored'"
  }
```
