### ISSUE TITLE
Results are url encoded

### ISSUE THREAD

**Issue by brookskindle** [joeferner/redis-commander#362]
# Summary
When viewing keys with special characters (I believe characters that require url encoding, though I only tested a few - see below), the results show up as url-encoded in redis-commander, where I would not expect them to be.

# Example
If I set a value via `redis-cli` that contains special characters 
```console
$ redis-cli set test '&<>'
OK
```

I would expect the output from `redis-cli` to match that of `redis-commander`
```console
$ redis-cli get test
"&<>"
```

but instead, the results appear to be url-encoded
<img width="241" alt="Screen Shot 2019-07-17 at 10 44 44 AM" src="https://user-images.githubusercontent.com/2654835/61397985-ec488780-a87f-11e9-8bd7-58135d81666a.png">

Is this intended behavior, or an issue?

**Comment by sseide** [comment]
Its an issue. Probably double encoded... I'll look into it.

**Comment by sseide** [comment]
should be fixed with latest version from github and new docker image. Can you have a look?

**Comment by brookskindle** [comment]
Yes, the issue I originally described looks like it's been fixed.

<img width="539" alt="Screen Shot 2019-07-29 at 1 32 40 PM" src="https://user-images.githubusercontent.com/2654835/62080466-97086080-b205-11e9-9a51-025c8d2a68c3.png">

---

<img width="572" alt="Screen Shot 2019-07-29 at 1 33 30 PM" src="https://user-images.githubusercontent.com/2654835/62080477-9bcd1480-b205-11e9-87b6-3927acdb8183.png">

---

<img width="461" alt="Screen Shot 2019-07-29 at 1 33 19 PM" src="https://user-images.githubusercontent.com/2654835/62080470-996aba80-b205-11e9-84a1-2c31f1dbcc5e.png">

I'll go ahead and close this issue - thank you for working on this!
