### ISSUE TITLE
REDIS_PASSWORD_FILE instead of plain password

### ISSUE THREAD

**Issue by sido420** [joeferner/redis-commander#364]
Is it possible to use something like `REDIS_PASSWORD_FILE` to specify redis password? This is to avoid having to put the password in env vars in plain text.

See https://hub.docker.com/_/mysql (under Docker Secrets for an example)

**Comment by sseide** [comment]
Not directly right now, only possible for the HTTP auth password (i'll update README  - is missing there for some reason).

Other workaround:
1. create a json config file with redis connection data and password and do NOT specify connection data via env vars at all. More possible values to configure connections can be found at the file `docs/connections.md`

```
{ "connections":[
   {"host":"1.2.3.4", "password": "secret"}
]}
```
2. bind-mount this file as `/redis-commander/config/local.json` inside your docker container.

Feel free to add PR with handling of `REDIS_PASSWORD_FILE` it if neded right now. Otherwise will be implemented whenever some finds some time for it...

**Comment by sido420** [comment]
I have never done it before but happy to do that if you could guide me how to do it. Github "pull request" doc was of no help.

Alternatively, here is the code for `entrypoint.sh` (line 157):

```
# load REDIS password from a file (e.g. a Docker secret mounted in the container)
REDIS_PASSWORD_FILE=${REDIS_PASSWORD_FILE:-/}

if [ -f $REDIS_PASSWORD_FILE ]; then
    REDIS_PASSWORD=$(cat $REDIS_PASSWORD_FILE)
    # this env var is evaluated by node-config module, not set as cli param
    # to not show it in process listing / write to docker logs ...
    export REDIS_PASSWORD="$REDIS_PASSWORD"
fi
```

**Comment by sseide** [comment]
Hi,

thanks for the diff. I changed it and commit to the repo.

Pull requests are not that complicated (i you have it done once...)

Things to do - if something unclear feel free to as:
1. You have to fork this repo (create your own version of it) -> on the github page of the repo press button "Fork" on the top right
2. Checkout your newly forked repo (git clone https://...) make shure you get your own forked one - your username is part of the url.
3. (Best practice but not needed) create new Branch inside your checked out copy, change to this branch (e.g. `git branch my-fix; git checkout my-fix`)
4. Make all the changes needed and commit + push
5. On github website, open your forked repo while you are logged in. Now (on the "Code" tab) you will see a text saying something like "This branch is 1 commit ahead of joeferner:master." Now press "Pull request"  on the right and than (if everything is green) "Create Pull Request" Button.

After the pull request is accepted you can delete this repo from github if you like.
Or - if you want to make more contributions do the following:
* here it is important that you work in a extra branch for everything you change, not at master branch!
* add the original git repo from redis-commander to your own checked out repo: `git remote add upstream https://github.com/joeferner/redis-commander.git`
* Now ou have your "origin" remote pointing to your github account and "upstream" pointing to the 
 base project repo.
* Whenever you want to sync with the original one go into your master branch and make a `git pull upstream master` to update your working copy with all code changes from the redis-commander repo. No you can merge your other branches with it and so on...

Best regards,
Stefan Seide

**Comment by sido420** [comment]
Thanks for the info. It will help me add PRs in future :)
