### ISSUE TITLE
Tagged releases on docker hub?

### ISSUE THREAD

**Issue by nabadger** [joeferner/redis-commander#365]
Hi, 

Are we able to get tagged releases on docker-hub? Seems a bit risky only having `latest`, plus this sometimes causes issues with caching (at least on kubernetes).

Given that we have actual tags on the git-repo, we could have automated-builds on the docker-hub side of things :)

**Comment by sseide** [comment]
may be worked on within #414

**Comment by sseide** [comment]
fixed - see #414 and #418 but on GitHub Container Registry only by now, Dockerhub releases will be available soon again (i hope)
https://github.com/joeferner/redis-commander/pkgs/container/redis-commander
