### ISSUE TITLE
ReJSON tree view support

### ISSUE THREAD

**Issue by funkyfisch** [joeferner/redis-commander#371]
Are there any plans of having the possibility to view ReJSON structures as a tree in redis commander? I wonder if it is a popular demand.

**Comment by sseide** [comment]
No plans right now. But PRs are welcome.

Out of curiosity - commands from ReJSON module are working inside Redis Commander cli? Nobody tested it up to now AFAIR.

**Comment by funkyfisch** [comment]
@sseide I have tested JSON.GET, JSON.SET and JSON.OBJKEYS successfully,
with redis-commander latest docker image (bc4791d91926)
and redis 5.0-alpine !

**Comment by funkyfisch** [comment]
So how about this:
Any keys in a Redis db with type "ReJSON-RL" (which seems to be issued by the redis db itself)
can be handled on a separate ejs template.

Right now I am almost done with this template, where you can view a formatted JSON document, inside a textarea field, a "copy JSON" button

In the back-end, i tried adding command definitions for the ReJSON module, but they use a . in their commands (e.g. JSON.GET) so that didn't work for me (unless I am missing something)
I discovered redisConnection.call() for executing raw commands, and now I am able to pull the entire document/value for any ReJSON-RL type key.

I will soon submit a PR. But in the meantime, please tell me if it sounds good so far, or if you would like some other small feature included with this

**Comment by sseide** [comment]
Hi - thanks so far.

And yes, it should be implemented via its own client-side ejs template under `web/static/templates`.
With redis server returning its own data-type it is straigth forward

a) own template to display data `web/static/templates`
b) optional own template to edit data or add to existing key via modal `web/views/modals` - e.g. similiar to lists (if needed)
c) modify generic "Add Key" modal to add JSON data (`web/views/modals/addKeyModal.ejs`)
c) modify inside `web/static/scripts/redisCommander.js` methods `loadKey()` and `getIconForType()`
d) inside `lib/routes/apiv1.js` add routes and methods to add/modify/delete this data if needed, update saveKey() method too (used for generic "Add Key")
e) in `lib/routes/apiv1.js` modify method `getKeyDetails()`

And as you already found out - most simple way to call these commands without ioredis having direct support is the `redisCon.call()` method (as in apiv1.js file postExec() method). Other variants  do not really work well. Sadly its not documented on ioredis side but works flawlessly.

And please only add only stuff needed to add ReJSON support to the PR. If you may yfind/fix/add others not related to ReJSON please create additional PRs.

Best regards

**Comment by bajohn** [comment]
> Hi - thanks so far.
> 
> And yes, it should be implemented via its own client-side ejs template under `web/static/templates`. With redis server returning its own data-type it is straigth forward
> 
> a) own template to display data `web/static/templates` b) optional own template to edit data or add to existing key via modal `web/views/modals` - e.g. similiar to lists (if needed) c) modify generic "Add Key" modal to add JSON data (`web/views/modals/addKeyModal.ejs`) c) modify inside `web/static/scripts/redisCommander.js` methods `loadKey()` and `getIconForType()` d) inside `lib/routes/apiv1.js` add routes and methods to add/modify/delete this data if needed, update saveKey() method too (used for generic "Add Key") e) in `lib/routes/apiv1.js` modify method `getKeyDetails()`
> 
> And as you already found out - most simple way to call these commands without ioredis having direct support is the `redisCon.call()` method (as in apiv1.js file postExec() method). Other variants do not really work well. Sadly its not documented on ioredis side but works flawlessly.
> 
> And please only add only stuff needed to add ReJSON support to the PR. If you may yfind/fix/add others not related to ReJSON please create additional PRs.
> 
> Best regards

Thanks for the idea - I was able to use this to pull Redis type `ReJSON-RL` into Nodejs via ioredis.
Here's a full snippet:
```
    const client = new Redis();
    const scanResp = await client.scan(0, 'COUNT', 10);
    const keys = scanResp[1];
    console.log(keys);
    const multiCommands = keys.reduce((lv, cv) => {
      return lv.call('JSON.GET', cv);
    }, client.pipeline());
    const rawResponses = await multiCommands.exec();
    const responses = rawResponses.map(el => JSON.parse(el[1]));
    console.log(responses);
```
