### ISSUE TITLE
Stop writing the redis password to the log file

### ISSUE THREAD

**Issue by allingeek** [joeferner/redis-commander#372]
`REDIS_PASSWORD_FILE` and other instances of the `*_FILE` environment variable pattern exist to facilitate more secure handling of credential material. Running `redis-commander` from within a container and using the `REDIS_PASSWORD_FILE` leaks that value in cleartext into the application logs.

If that or other `_FILE` environment variables are set the container entrypoint script should not log the command used to execute redis-commander.

**Comment by sseide** [comment]
using config files myself not noticing it... Better now?
Availabe from github master or latest dockerhub image.

**Comment by sseide** [comment]
Can you please confirm if this is fixed with current version? Can this ticket be closed now?

**Comment by sseide** [comment]
closed due to lack of response / interest of author
