### ISSUE TITLE
no explanation for K8S_HANDLE envvar in k8s/redis-commander/deployment.yaml

### ISSUE THREAD

**Issue by no2a** [joeferner/redis-commander#379]
What is K8S_HANDLE=1 in the deployment.yaml ?

https://github.com/joeferner/redis-commander/blob/898b6756ed3e673f8f761324e200755cb55e26b6/k8s/redis-commander/deployment.yaml#L22

I grepped all files in the repo, but no other line refers it.

**Comment by sseide** [comment]
thanks - should read `K8S_SIGTERM` - and this is described inside README.

example updated.
