### ISSUE TITLE
How to set volume ?

### ISSUE THREAD

**Issue by rawipon-t** [joeferner/redis-commander#380]
Please show me the example for set the volume in docker-compose file.

Thank you

**Comment by kveroneau** [comment]
I was wondering the same thing, as this Redis UI definitely uses persistent data which will be lost if you remove and recreate the container by say updating your version of redis-commander.  I used the `docker diff` command to determine what files within the running container were changes and determined the configuration file you can map into your host is `/redis-commander/config/local-production.json`, so you can either bind mount this file, or use a volume for `/redis-commander/config`.  Hope that helps with your docker-compose configuration.

**Comment by sseide** [comment]
@kveroneau your assumption about persistent data is partly wrong - it does create this `local-production.json` file, but this one is automatically created from the env vars set for starting this container. And this file is overwritten on every restart. Therefore persisting it is completly useless. 

It may seem to help if you do not configure every redis connection on startup but add/remove redis servers later on during runtime - they are saved there. But as i said, this file gets overwritten on next startup whenever an env var related to redis connections is set. 

It may help only  to mount a config file if you have your own one to set other config parameters as you like without using env vars or define a much broader list of redis-connections as its possible via env var (as mentioned/suggested inside the redis commander docs). And this behaviour with the config files is documented directly under "Configuration" in the readme...

So the inital question - the first answer asking google presents an answer: https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume
or the docker-compose documentation itself at https://docs.docker.com/compose/compose-file/#volumes

And the issue author does not stated what he really want to do or reach - this very generic question can be completely answered by the docker documentaton alone. Cannot see something special or non-working stuff here...

**Comment by sseide** [comment]
Closed as there are no further updates from author how issue is related to redis commander.

@kveroneau if you have some more questions or remarks on how to handle your specific requirements feel free to open a new issue.
