### ISSUE TITLE
Browser crashes on Large keys list

### ISSUE THREAD

**Issue by shojaeix** [joeferner/redis-commander#384]
I have a serious problem with large keys list(keys=61685,expires=61676). 
When i open dashboard, it uses over 800mb of Ram and overload the cpu, then browser crash as result.

is there any way to keep keys list close ? (most of the time i just need CLI)

**Comment by sseide** [comment]
Can you please explain a little more about your database layout?
Entire db contains 61000 keys? Or is a list (set) entry containing 61k values?

If it are db keys - what are the names of it (structure wise)? Are (nearly) all keys are displayed on the top level of the tree view on the left? Or are there only some keys on the top level and it is nested with multiple (sub-)folders. Whats the bigger sizes of the folders than (the number behind the virtual folder name).

If it crashes before displaying it - you probably now how the names are created within your db. The default folder-separator for the UI is ":". Do your key names contain this character or not?

As by now there is now way to not display at least the first level of the tree view of the first connection entry. But config param to not open it can be added...

Workaround may be to add another redis connection as first connection (top of tree view) which does not contain that much keys and can be opened without overloading the UI (e.g. use REDIS_HOSTS env var on docker or modify config file if run without docker).

**Comment by shojaeix** [comment]
@sseide  Thanks for your time and detailed explanation.
Entire db contains 61k keys.  all keys displayes on top level(Because keys seperated by underline, not colon) 
Can i change the default key seperator in dashaboard? or must change keys name? 

It was my obvious mistake, i thought the Redis-Commander first load all keys from server then grouping them.  Sorry about that.

**Comment by sseide** [comment]
Ok, i hope changing the separator helps. There are different ways to do ths - depending on how you start redis commander one or the other might be easier to use:

* create/modify your own local config file `config/local.json`
  ```
  { "ui": { "foldingChar": "_" } }
   ```
* add command line parameter `--folding-char _`
* set environment variable `FOLDING_CHAR=_`

Nonetheless i will some time in the future  try to look into it if there are ways to reduce the memory needed for the tree view...
