### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by LuckyDogg** [joeferner/redis-commander#386]
when i run redis-commander ，the error log：
Invalid Login: Error: All sentinels are unreachable. Retrying from scratch after 10ms. Last error: Connection is closed.
connecting sentinel...  xspider [{"host":"@type","port":null},{"host":"val","port":null}]

but I do not have the redis: xspider

**Comment by sseide** [comment]
Somehow you configured it to connect to a redis sentinel instance with this name. Without knowing how you start it nobody can help you... please provide some more informations

**Comment by sseide** [comment]
some more informations or did you solve your problem?

**Comment by sseide** [comment]
closed due to missing feedback
