### ISSUE TITLE
Support windows backslash based paths for module resolution

### ISSUE THREAD

**Issue by JacquesJamiesonLancom** [joeferner/redis-commander#388]
Currently running redis commander on windows is a now go, i get the following error trying to start

```
C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\lib\app.js:86
  return require.resolve(module).match(/.*\/node_modules\/[^/]+\//)[0];
                                                                   ^

TypeError: Cannot read property '0' of null
    at modulesPath (C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\lib\app.js:86:68)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\lib\app.js:132:59)
    at startWebApp (C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js:567:21)
    at C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js:489:12
    at startDefaultConnections (C:\Users\jacquesj\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js:515:10)
    at startAllConnections (C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js:483:3)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js:293:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

An example path output from just running `require.resolve('jstree')` manually gives this path.

```'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\redis-commander\\node_modules\\jstree\\dist\\jstree.js'```

**Comment by JacquesJamiesonLancom** [comment]
@sseide i followed the install from readme. So i would assume that uses the version in NPM? 

Apologies if this is a duplicate issue, i tried searching.

**Comment by sseide** [comment]
No problem - and as the pull request was already closed it was not that easily to spot. There was no  issue for that up to yours, only the PR.

Most people probably do the `npm install` way. But changing installation to  a `git clone` and using the latest from there does fix your problem?

p.s. if you do not want to get full history from git a `git clone --depth 1 https://github......` reduces download size a lot if you are only interested in the latest version of the master branch.

**Comment by wrabbit23** [comment]
Glad to hear this is already fixed!  Replying here so I will get notify when it is closed (published to npm).  

For those of us on Windows who are too lazy to clone, installing 0.6.5 is a work around.

**Comment by sseide** [comment]
0.6.5 has a dozen other bugs already fixed in 0.6.6/0.6.7. For these lazy ones I would suggest downloading the zip from github and running `npm install` inside the unzipped directory as a better alternative...

Sorry to see this coming up shortly after latest release as the change responsible was there for a long time without reports.

**Comment by JacquesJamiesonLancom** [comment]
Apologies for delay in response, Yeah master clone worked a charm. Is deployment to npm manual or do you have a task that does this after merge into master? I would be happy to send a pr for deploying to npm automatically

This issue can be closed now since its fixed and i have a work around.

**Comment by sseide** [comment]
I will leave this issue open as long as there is no fixed npm version available (for others to find it easier). Will close it after new version is released.

Regarding npm - its manually. Maybe Joe Ferner will accept a PR for automatic publish of tagged versions but i do not know...

**Comment by alrabe** [comment]
It might be helpful for people without Node background to show how to run this from the CLI. I did:
clone the repo, did a 'npm install', and typed 'node bin/redis-commander.js'. Now I wonder waht to do with this information: setUpConnection (R:undefined:undefined:undefined) Redis error Error: connect ECONNREFUSED 127.0.0.1:6379

**Comment by sseide** [comment]
thats where the "usage" and/or "configuration" chapter of the readme are relevant - to configure the redis server you want to reach... Without saying the app (from here its just a normal app like everything else, nothing node-specific) where to find its database to display it assumes you run a local redis and tries to connect to it.  May be true or not. Depends on your setup. But does not differ from all the other Database tools out there. Or you open the app and add connections via the grafical user interface

If you have some suggestions on how to improve the readme PRs are welcome. Or additonal quickstart markdown file (linked from the main readme) in the docs/ folder...

**Comment by ynaciri** [comment]
Hi there, I tried using the solution with v0.6.6 and the bug is corrected.

Unfortunately, when I tested the same thing on v0.6.7 this bug came back :(

**Comment by supertiger1234** [comment]
Could anyone show me the exact commands to install the working one? :( I wanna use this again.

**Comment by sseide** [comment]
```
git clone https://github.com/joeferner/redis-commander.git
cd redis-commander
npm install
```

**Comment by ethanresnick** [comment]
@sseide @joeferner Is there anything preventing the fixed version from being published on npm now (as a patch release)? I work in an org where installing code from Github is not allowed; instead, we must install through (an on-prem and security-screened clone of) the npm repository, so getting this fix into npm would be immensely helpful for me and my colleagues. Thanks

**Comment by sseide** [comment]
i prepare a new version today but need to update some dependent libraries before to fix some open security warnings.

**Comment by joeferner** [comment]
v0.7.0 released

**Comment by ethanresnick** [comment]
Thanks!
