### ISSUE TITLE
RedisJson

### ISSUE THREAD

**Issue by danleighton** [joeferner/redis-commander#392]
Is adding json datatypes on the roadmap by any chance if you are using RedisJson/2? I did spot that I could add JSON objects on the CLI but there's not the ability to add them yet in the UI. I also spotted that they could be added (great documentation) it's just not the kind of thing I could trust myself to do and not screw up!

Great work on this application. Really nice to have an alternative to the non-open source RedisInsight...

**Comment by sseide** [comment]
Hi, as current development is most spare time features we need ourself are on the top of the list. And adding JSON data are not planned by now... Sorry about that.
