### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by gamevnlc** [joeferner/redis-commander#398]
I have ran to this issue when run `redis-commander` on cmd. My Os version is Windows 10
Full report

![image](https://user-images.githubusercontent.com/2215185/76539313-2e7ba480-64b3-11ea-99cd-395903b0d308.png)

**Comment by Celludriel** [comment]
I got the same problem after a full fresh install

Windows 10
Node version: 12.16.1 LTS

**Comment by sseide** [comment]
duplicate of #388
