### ISSUE TITLE
Working fine without auth, but not working with http_user and http_password

### ISSUE THREAD

**Issue by surajmodi90** [joeferner/redis-commander#401]
When I add HTTP_USER and HTTP_PASSWORD, the login prompt loops infinitely.
I looked at the container logs and looks like login succeeds, but the browser console complains about no token.

I removed USER and PASSWORD from the ENV variables and it works fine. 

Please fix the auth issue! This used to work fine few months ago.

These are the web browser console logs (using chrome on a mac)
Failed to load resource: the server responded with a status of 401 ()
responseText: "Unauthorized - Token Invalid or Expired"
status: 401
statusText: "error"

**Comment by sseide** [comment]
a little bit more informations would help to better understand your issue. AS we have no problem with this at our side.

What url got an 401? Do you tried a full reload in the browser?
Are there error messages server-side? Are there other messages around this one? Please post the full console log.

And there was not changed anything for a longer time. If you say it worked before - what version of redis commander was it? Do you switched back to the old version and its working than again?

**Comment by sseide** [comment]
Any feedback or is this resolved?

**Comment by sseide** [comment]
closed  (no feedback and unable to reproduce)
