### ISSUE TITLE
Unable to connect Remote Redis

### ISSUE THREAD

**Issue by cah-manish-kumar05** [joeferner/redis-commander#402]
While Trying to connect Remote Redis instance hosted on PCF Shared VM, its failing with time out error as below -
`Redis error Error: connect ETIMEDOUT`

**Comment by sseide** [comment]
as message states the redis commander container cannot talk to your redis server. Without further infos we cannot really help.

Therefore please check:
* port configured is the port the redis server listens to
* dns-name or ip given to redis commander as redis server is correct
* dns-name can be resolved from inside the container
* final ip address the server name resolves to can be reached from inside the container (ip route exists and no firewall is blocking communications)

**Comment by sseide** [comment]
Issue closed by now?

**Comment by sseide** [comment]
close (no feedback and unable to reproduce)
