### ISSUE TITLE
Authentication no longer working after updating to Redis 6

### ISSUE THREAD

**Issue by TheRealChrisS** [joeferner/redis-commander#403]
Hi,

we updated our Redis test server to Redis 6 yesterday. Since then the redis-commander is no longer able to authenticate (while our applications using it still can). We use the following command to run redis-commander:

`docker run --rm --name redis-commander --env REDIS_HOSTS=RedisTest:our_redis_host:6379:1:some_password -p 8181:8081 rediscommander/redis-commander:latest`

We now get this error:
```
Redis error ReplyError: WRONGPASS invalid username-password pair
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14)
```

The password stays the same and we did not start to use ACL, we just change from Redis version 5 to Redis version 6 in Dockerfile.

Are we doing something wrong or is redis-commander not yet ready for Redis 6?

Thanks,
Christian

**Comment by sseide** [comment]
command line looks right.
but have not tested it against redis 6 by now, maybe something change here...

**Comment by sseide** [comment]
maybe related to this: https://github.com/luin/ioredis/issues/1097
something definitly changed in redis 6 but changelog of redis itself is not mentioning it. :-/

**Comment by sseide** [comment]
just testet with latest redis from dockerhub (6.0.1) and started with `requirepass foobared` setting activated. Now authentication is required but login possible with redis commander as usual...

Can you please give the entire redis server config - at least the auth/acl/security related settings?
I cannot reproduce it locally with latest version.

**Comment by TheRealChrisS** [comment]
I also pulled the latest Redis version (6.0.1) and now it's working again.

**Comment by 3p3r** [comment]
without the `requirepass` option and using just ACLs, I don't think it's working. How do I supply my username?

**Comment by sseide** [comment]
@3p3r using new Redis 6 acls with username/password is currently not supported.
Inside ioredis lib there where some incompatibilities with this but now it seems stable/usable.
Now Redis commander can be updated to allow setting a username too..

PR anyone?

**Comment by sseide** [comment]
created #411 to track this

**Comment by sergeyampo** [comment]
Waiting for update
