### ISSUE TITLE
Command entry mode needs to stretch the full width to allow for longer queries

### ISSUE THREAD

**Issue by schwab** [joeferner/redis-commander#404]
Currently the command line window at the bottom only displays the first 80 characters or so.  In doing so it arbitrarily cuts off long queries.  This is especially annoying when trying to debug long redis graph queries for instance.  Please allow the text box to expand full width of the screen.  Even better would be a multi-line box which can be resized to allow for even longer blocks of text.

**Comment by sseide** [comment]
updated line width to available space. But its single line only. Have to do some deeper check for multi line input. And there is a related issue #367 to allow multi line inputs as well. 

If its working for a single line better now i like to close this one in favor of the other issue to handle multi-line inputs...

**Comment by schwab** [comment]
Thank you that will help a lot.
