### ISSUE TITLE
Feature request: Only display values less than configureable max len str

### ISSUE THREAD

**Issue by chrisregnier** [joeferner/redis-commander#409]
First, thanks for the super useful tool!

I have a problem when viewing hashes with key/values that have large sizes (1MB - 50MB range). It basically crashes the browser cause it's trying to load lots of data when I click to view the hash.
Is it possible to add a configurable max size limit on values so it won't automatically load and display large values. Instead it can display a message "Large value, click here to view" to allow the user to click on it if they really want to request/display it.

**Comment by sseide** [comment]
yes, would probably helpful for such cases. 

As there is not much spare time right now, help is appreciated

**Comment by chrisregnier** [comment]
I've already found usage much snappier over the past week of using the new option. Thanks for merging it in!
