### ISSUE TITLE
Add support for new Redis 6 acls with username/password

### ISSUE THREAD

**Issue by sseide** [joeferner/redis-commander#411]
With latest ioredis lib its possible to use a username/password to access a redis 6 server with acls configured.

Redis-Commander does not support usernames by - this feature can be added.

* check username/password against Redis 6
* configuration of username via
  - cli
  - env var
  - config file
  - web-ui to add new server on-the-fly
* check username/password against Redis 6 Sentinel (ACL possible there too?)
* configuration of sentinel username through all ways outlined above

**Comment by amirulabu** [comment]
Is anyone picking this up? If not, I might have a go on it.

**Comment by sseide** [comment]
there was a pr #476 and should be working now. Published as Version 0.8.0

Please check and report if there are some problems
