### ISSUE TITLE
Release Images with version tag on Dockerhub

### ISSUE THREAD

**Issue by steinbrueckri** [joeferner/redis-commander#414]
At the moment the only useful tag on DockerHub is the latest tag, but this is not optimal.

![image](https://user-images.githubusercontent.com/578303/87922871-debe7280-ca7c-11ea-8f81-62f52805f9f0.png)

Maybe i can find some time to build a GitHub action workflow for that.

**Comment by sseide** [comment]
yes, you are right - having this would be helpful be needs to be added be Joe Ferner then..

**Comment by steinbrueckri** [comment]
loop @joeferner

**Comment by sseide** [comment]
there is a pull request to use github actions to build images for different architectures at once. 
This could be enhanced to create tagged images too on pushing a new tag to the repo...

**Comment by thomastvedt** [comment]
+1 for adding version tags

Tagging releases with an actual version number would enable us to setup Dependabot to listen for new versions of Redis commander and create PRs automatically.

**Comment by sseide** [comment]
implemented but published to GitHub Container Registry only right now. Will try to fix DockerHub releases too.

https://github.com/joeferner/redis-commander/pkgs/container/redis-commander

Version tags start with next version released. Currently "latest" only

**Comment by thomastvedt** [comment]
> https://github.com/joeferner/redis-commander/pkgs/container/redis-commander

Hi, when will the next "real" version be tagged and released? Any chance you could release a version now? :)

**Comment by thomastvedt** [comment]
Doesn't look like this is working as intended? No version tags yet, only latest 🤔

**Comment by sseide** [comment]
because no version was released by now. Currently waiting for a feedback at #466 from @themizzi if the update is working or not to not release a broken enhancement...

**Comment by thomastvedt** [comment]
Ahh I see, I'll just try to be a bit more patient then 😅

**Comment by sseide** [comment]
@thomastvedt now there is a release 0.8.0 available as docker image and on npm.
just check https://github.com/joeferner/redis-commander/pkgs/container/redis-commander again. 

Sorry for the delay - hoped to fix all vulnerabilities but some of them do not have upstream fixes by now...
