### ISSUE TITLE
How to provide Certificate's public key

### ISSUE THREAD

**Issue by tsrana** [joeferner/redis-commander#415]
I wanted to use docker image. For connecting localhost redis it is working good but my production Redis server used password and Certificate's public key. 
I am not getting a way to connect prod redis by using Certificate.

**Comment by sseide** [comment]
as mentioned in the documentation you need to create your own json config file and set the "tls" attribute accordingly to contain your client cert: [docs/connections.md](https://github.com/joeferner/redis-commander/blob/master/docs/connections.md#connection-parameters)

This config file must be mounted into the docker container on startup (https://github.com/joeferner/redis-commander/blob/master/docs/connections.md#connect-to-tls-secured-redis-inside-docker-container)

**Comment by sseide** [comment]
did you get it working? Can you close this issue?

**Comment by sseide** [comment]
closed as there is no feedback, problem solved it seems
