### ISSUE TITLE
How I can disable replications of a connection to the redis master

### ISSUE THREAD

**Issue by MY23** [joeferner/redis-commander#417]
Hello everyone,
I am having a problem replicating the same connection to the redis master after deploying this tool to our kubernetes cluster and after a few moments I noticed that a replication is added!
![image](https://user-images.githubusercontent.com/38831358/95437217-a37d6280-094c-11eb-80ec-a6d1ac8680fe.png)
is there any solution for that ? 
Thanks.

**Comment by sseide** [comment]
Never seen this before. Without knowing how you configure and start it we cannot help here.
e.g. custom config file, command line parameter, env variables?
Default docker image or self build?

**Comment by MY23** [comment]
thanks for the reply
this is my deployment file :
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.redis.commander.deployment.name}}
spec:
  replicas: {{.Values.redis.commander.deployment.scale}}
  selector:
    matchLabels:
      app: {{.Values.general.microserviceName}}
      type: {{.Values.redis.commander.deployment.type}}
  template:
    metadata:
      labels:
        app: {{.Values.general.microserviceName}}
        type: {{.Values.redis.commander.deployment.type}}
        tier: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hold-tools
                operator: In
                values:
                - "false"
              - key: hold-microservices
                operator: In
                values:
                - "true"
              - key: elk
                operator: In
                values:
                - "false"
              - key: environment
                operator: In
                values:
                - "development"
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: {{.Values.redis.commander.deployment.containerName}}
        image: {{.Values.redis.commander.deployment.image}}
        env:
        - name: REDIS_HOSTS
          value: instance:redis:{{.Values.redis.master.service.servicePort}}
        - name: K8S_SIGTERM
          value: "1"
        ports:
        - name: redis-commander
          containerPort: {{.Values.redis.master.service.servicePort}}
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
          limits:
            memory: "200Mi"
            cpu: 0.3
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL`
ingress :
`---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-with-auth
  namespace: {{.Values.general.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/secure-backends: "false"
spec:
  rules:
  - host: {{.Values.redis.commander.ingress.host}}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{.Values.redis.commander.service.name}}
          servicePort: {{.Values.redis.commander.service.servicePort}}
...`
and service :
`---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redis.commander.service.name}}
  namespace: {{.Values.general.namespace}}
  labels:
        app: {{.Values.general.microserviceName}}
        type: {{.Values.redis.commander.deployment.type}}
        tier: backend
spec:
  selector:
    app: {{.Values.general.microserviceName}}
    type: {{.Values.redis.commander.deployment.type}}
    tier: backend
  ports:
  - port: {{.Values.redis.commander.service.servicePort}}
    targetPort: {{.Values.redis.commander.service.serviceTargetPort}}
    name: {{.Values.redis.commander.service.name}}
...`

**Comment by sseide** [comment]
This is not the deployment descriptor for the screenshot you provided.
In the deployement a connection with name "instance" is created - the screenshot connections are all named "DATABASE".
And the desciptor connects to a host named "redis" (DNS name) where the screenshot shows "redis-master".

And finally - kubernetes has no persistent storage per default - but this would be needed to add one connection on every restart. Connection information from REDIS_HOSTS env var are stored inside the file "config/production-docker.json". But this file is deleted on every container restart without a persistent storage...

So question remains - what do you really do?

**Comment by sseide** [comment]
And its on purpose that you assign redis commander the same port as your redis server?
The `{{.Values.redis.master.service.servicePort}}`...

**Comment by MY23** [comment]
Thanks for your help @sseide i solved the problem

**Comment by gwillyoo** [comment]
@MY23 How do you solve it?

I have the same issue. I use the latest docker (the docker is updated 3 days ago, when i post this.) with no configuration changes except i add my redis server.

![image](https://user-images.githubusercontent.com/38490181/99842361-422eed00-2ba2-11eb-90a6-3bab43b702df.png)

I have reproduced it. From what i found the cause is when connecting to my redis-server, i change the connection using vpn and then revert back without vpn. I refreshed the web gui, it created same connection.

![image](https://user-images.githubusercontent.com/38490181/99842662-d8fba980-2ba2-11eb-82f3-3c521ec58cd5.png)

**Comment by MY23** [comment]
I just corrected the env record:
`env:
          - name: REDIS_HOST
            value: "REDIS MASTER HOST"
          - name: REDIS_PASSWORD
            value: "PASSWORD"
          - name: REDIS_PORT
            value: "6379" 
`
