### ISSUE TITLE
Bad JS load path when URL missing trailing slash

### ISSUE THREAD

**Issue by mcandre** [joeferner/redis-commander#419]
Remember to prefix assets with a forward slash so that they're not relative. Blank white screen.

**Comment by sseide** [comment]
some more information please? Where exactly do you spotted this problem?

**Comment by sseide** [comment]
As this report was not really descriptive and I could not reproduce it, i'm not sure if your problem may be fixed with latest version. Added validation to urlPrefix there...

**Comment by sseide** [comment]
closed as there is no feedback and i believe its fixed with later releases. Please reopen with more details if not fixed
