### ISSUE TITLE
Undesirable newlines & whitespaces in hash edit popup

### ISSUE THREAD

**Issue by AntoineLemaire** [joeferner/redis-commander#426]
Hello,

Since https://github.com/joeferner/redis-commander/pull/410/files#diff-d9a68badafe3e8b5e2fb137e50536ad72dbd1d6108f3a345b9a9c6f6fcec6de7R32-R38, when I edit a has field, the value comes with newlines & whitespaces before & after the value.

![image](https://user-images.githubusercontent.com/2025537/100882278-4bc42900-34af-11eb-8a56-55138abd88a7.png)

It's because the `<td>` is generated with that, and we use the `<td>.innerHTML.toString()` to get the value for the popup (https://github.com/joeferner/redis-commander/blob/master/web/static/templates/editHash.ejs#L57)

![image](https://user-images.githubusercontent.com/2025537/100882391-71e9c900-34af-11eb-80e1-a9b31beba498.png)

**Comment by sseide** [comment]
I see - but this fix doubles the data inside the html tree giving memory problems on bigger objects.
I created another fix using ejs template based whitespace trimming. Will test and push in some minutes

**Comment by AntoineLemaire** [comment]
Yes, you're right I didn't thought about that. 
I tried with `<%- -%>` or `<%_ _%>` but I never worked with EJS and I failed.
Thanks for helping

**Comment by sseide** [comment]
No problem :-) Thanks for bringing up this issue and adding a PR. Really appreciated it and was way faster to solve it through this (easy to understand then)

please check again - should be fixed now and preserve trailing/leading white spaces of value itself.
New docker image is building...

**Comment by AntoineLemaire** [comment]
Yes, everything is good on my side, I close this issue! :partying_face:
