### ISSUE TITLE
docker container is trying to bind to host IP address?

### ISSUE THREAD

**Issue by justinrush** [joeferner/redis-commander#428]
It looks like the docker container is trying to bind directly to the host ip rather than localhost or 0.0.0.0 which causes issues because I have other containers listening on port 8081 already.  Is there a an env var I'm missing somewhere that let's me try and bind this to 0.0.0.0?

```bash
docker run -e HTTP_USER=guest -e HTTP_PASSWORD=guest -e ADDRESS=redis -p 7000:8081 artifactory.epic.com/docker/rediscommander/redis-commander
```

```
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander
Using scan instead of keys
No Save: false
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 192.168.0.100:8081
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1493:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '192.168.0.100',
  port: 8081
}
```

**Comment by sseide** [comment]
Redis Commander just did what you said it to do...

You mixed up the environment variables - ADDRESS defines the ip address to use to bind its local server to. This env var  should not be set running in docker (it defaults to 0.0.0.0 there) . Its for running a local installation checked out from git or installed via npm.

Redis server related configuration is defined via REDIS_* env vars.
