### ISSUE TITLE
Cannot Connect to Multiple Redis Hosts

### ISSUE THREAD

**Issue by alexgaganashvili** [joeferner/redis-commander#429]
Hello,

When I provide a comma-separated list of redis hosts, I get the following error:

```
setUpConnection (R:localhost:6379:0) Redis error Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
setUpConnection (R:my-redis-master-0.my-redis-headless:6379:0) Redis error ReplyError: NOAUTH Authentication required.
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14)
redis command "command" not supported, cannot build dynamic command list for (R:my-redis-master-0.my-redis-headless:6379:0
ReplyError: NOAUTH Authentication required.
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '0' ] }
```

The following is the value I have set in the values.yaml:

`hosts: "my-redis-master-0.my-redis-headless,my-redis-slave-0.my-redis-headless,my-redis-slave-1.my-redis-headless,my-redis-slave-2.my-redis-headless"`

It only works with a single host, e.g.:

host: "my-redis-master-0.my-redis-headless"

Please advise.

Thanks,
Alex

**Comment by sseide** [comment]
How do you started redis commander (direct install via npm, as docker image, ...), and what values.yaml?
Please be more specific about what you have done for people to help you...

**Comment by alexgaganashvili** [comment]
I used the helm chart from `https://github.com/joeferner/redis-commander/tree/master/k8s/helm-chart` to generate a Deployment manifest. The image being used is rediscommander/redis-commander:latest. I already provided the values I use for redis hosts when I opened the issue.
Please provide instructions in the README of https://github.com/joeferner/redis-commander/tree/master/k8s/helm-chart on how to deploy redis-commander with support for multiple redis hosts.

Thanks.

**Comment by alexgaganashvili** [comment]
It looks like it's a known issue:

```
known issues with Kubernetes:

using REDIS_HOSTS works only with a password-less redis db. You must specify REDIS_HOST on a password protected redis db
```
