### ISSUE TITLE
Duplicated local Server apeared

### ISSUE THREAD

**Issue by yorkane** [joeferner/redis-commander#432]
As you see below, all servers are the same single local server : Pikadb (compatible with Redis protocol)

![image](https://user-images.githubusercontent.com/11476816/104848182-c5f52380-591e-11eb-96d6-c3d376110889.png)

**Comment by sseide** [comment]
without knowing the version you use, how you installed it, how you started it and whats your config files people can only guess whats happening.
And logfiles from app itself help too...

**Comment by sseide** [comment]
closed as not reproducible and no response from author
