### ISSUE TITLE
Connection to local docker redis problem

### ISSUE THREAD

**Issue by adeda** [joeferner/redis-commander#437]
Hello, 
I have a problem connecting to local redis running on docker container. 
I did something like:
sudo docker run -it --rm --name redis -d -p 6379:6379 redis:6.0.10-alpine
and 
docker run --rm --name redis-commander -d --env REDIS_HOSTS=redis:127.0.0.1:6379 -p 8081:8081 rediscommander/redis-commander:latest

but can't connect with GUI (ERROR: Status: reconnecting)
(the same without REDIS_HOSTS)
Any clue I would appreciate
Thanks in advance

**Comment by axelrindle** [comment]
The IP address `127.0.0.1` points to the local container `redis-commander`. You need to specify the IP address of the container `redis`. You could also use `docker-compose` where you can use the container name instead (which would be `redis`).

**Comment by sseide** [comment]
to explain the comment from @axelrindle a bit more:

Redis commander and Redis database are booth running inside their own container. 
You asked Redis commander to connect to localhost from inside the Redis commander container -> thats the redis commander container itself. "localhost" as seen for redis commander is not your computer (where you exposed the redis ports to).

That said, you have to supply your hosts ip address the Redis commander container can reach (e.g. your computers local networks 192.168... or 10.... address). Thats a problem running booth containers independent by docker itself...

**Comment by sseide** [comment]
@adeda your problem is solved? Can this issue be closed?

**Comment by adeda** [comment]
Resolved, thanks

**Comment by AirborneEagle** [comment]
@adeda what was your solution? I am running into the same issue
