### ISSUE TITLE
Trouble with coding, version latest from dockerhub.

### ISSUE THREAD

**Issue by motionrus** [joeferner/redis-commander#443]
![image](https://user-images.githubusercontent.com/14940768/113587171-171bd600-9637-11eb-9279-b66ccb028939.png)

Trouble with coding, version latest from dockerhub. Please help me. Thanks

**Comment by sseide** [comment]
As redis does not have any information about string encodings there is no way to select the appropriate one if its not UTF-8. Or to tell if its really a string or binary. Redis wont tell you. The UI has to guess.

For binary data special handling is implemented for string type only so far. Nothing for set/list/hash/...

**Comment by sseide** [comment]
closed due of missing feedback
