### ISSUE TITLE
Redis error Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by sprudel79** [joeferner/redis-commander#453]
Hi everyone,
I am trying to use the redis-commander via Docker.
Locally I am running the Redis instance like this:
`docker run --rm -p 6379:6379 --name redis redis`

I can connect to this local instance via "redis-cli".
Now I am trying to run redis-commander via:
`docker run --rm --name redis-commander --env REDIS_HOSTS=localhost -p 8081:8081 rediscommander/redis-commander:latest`

What I get is this:
setUpConnection (R:localhost:6379:0) Redis error Error: connect ECONNREFUSED 127.0.0.1:6379

However, when I start redis-commander directly via NPM:
```
$ npm install -g redis-commander
$ redis-commander
```
it's working without any issues.
I have also tried to pass no REDIS_HOSTS or to set 127.0.0.1 and even the port, but it doesn't help.

Could anyone please tell why?
Thanks in advance!

**Comment by sseide** [comment]
AFAIR Mint is starting a firewall - you need to open the port to allow connections to redis server.
As i said - have you tested to access the redis server from you local system with the ip mentioned? Does this work?

```
redis-cli -h 192.168.153.102
```
and then send redis command like "`keys *` or `select 1`.
if `redis-cli` command is not known install client tools via `apt-get install redis-tools`
