### ISSUE TITLE
Using redis locally with docker, ECONN incorrect password

### ISSUE THREAD

**Issue by smolinari** [joeferner/redis-commander#460]
Hi,

I'm using redis locally and was trying out redis-commander as a docker container, but with it, I get the ECONN failure with incorrect password. Running redis-commander as an npm install works flawlessly. Is there something I can check on the docker side? Everything works, just not the connection request.

Scott

**Comment by sseide** [comment]
As there are no information given on how you started / configured Redis Commander i can guess only. But as its working with local installation but not inside the container it is for sure the wrong host name for the Redis server you have given to Redis Commander. Docker creates kinda virtual hosts for every container running (with its own ip address) and you have to give it the right address to connect to the server, (hint: it is not "localhost"). 

Reading about docker networking will help a lot for understanding about this problem (and with every other service you deploy via docker)

**Comment by smolinari** [comment]
@sseide - Thanks. It was the name of the redis service that I had to enter into the hostname field. Now it is working. 

Scott
