### ISSUE TITLE
How to diagnose a connection problem? "ERROR: Status: connect"

### ISSUE THREAD

**Issue by iamphi** [joeferner/redis-commander#465]
I have an AWS Elasticache cluster (redis 5.0.6). I can connect to it using:
`docker run -it --rm redis redis-cli --verbose -h ***.cache.amazonaws.com --tls --insecure`
Notice that I have to use `--insecure`

However when I try to use redis-commander:
` docker run -it --rm --env-file redis.env -p 8081:8081 rediscommander/redis-commander`
I get this error in redis-commander's web console:
"ERROR: Status: connect"
redis.env has
```
REDIS_TLS=true 
REDIS_HOST=***.cache.amazonaws.com
REDIS_PASSWORD=***
```

How can I further diagnose this issue?
Thank you.

**Comment by sseide** [comment]
try setting additional env var `NODE_TLS_REJECT_UNAUTHORIZED=0` (https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue) to disable certificate validation. I suspect problem arises from certificate either being self-signed or signed by an unknown CA. This env var disables certificate checks to be signed by a trusted root cert.

Another thing running `openssl` command line client to check certificate directly and see if it is a trusted one or signed by someone unknown:
```
openssl s_client -connect ***.cache.amazonaws.com:6379
```
and check output of the certificate chain who is the original root ca cert here.

To solve the problem (if it is a self-signed or unknown CA) you need to add this root ca certificate to redis commanders local certificate store to allow Nodejs to connect to these servers. Using  `NODE_TLS_REJECT_UNAUTHORIZED` is only a insecure workaround.

To trust a specific CA certificate set `REDIS_TLS` env var to a json string with
```
{"ca":"<content_of_ca_cert_pem_file_with_linebreaks_as_\n"}
```
see https://ioredis.readthedocs.io/en/stable/README/#tls-options

**Comment by iamphi** [comment]
Unfortunately `NODE_TLS_REJECT_UNAUTHORIZED=0` did not help.
Excerpt of the openssl command
```
CONNECTED(00000003)
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = *.cccccc.bbbbb.aaa.cache.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/CN=*.cccccc.bbbbb.aaa.cache.amazonaws.com
   i:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
 1 s:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
   i:/C=US/O=Amazon/CN=Amazon Root CA 1
 2 s:/C=US/O=Amazon/CN=Amazon Root CA 1
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
 3 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
   i:/C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
xxxx
-----END CERTIFICATE-----
subject=/CN=*.cccccc.bbbbb.aaa.cache.amazonaws.com
issuer=/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5115 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 1BFF846257522719FF5F8A4361C456875C5E22BB60F9F098B781A01904E0104E
    Session-ID-ctx:
    Master-Key: 31AB1BB12538735DB42BF8A85D7E4FA4849F4C4681650375D0D3FD5DE145E40AC670FCCD0A7755C3CAE3473C70256BFC
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1644444088
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

```

**Comment by sseide** [comment]
right now seen this:
> I get this error in redis-commander's web console:

What messages do you get in ther server-side console? The redis-commander server connects to redis only.
The web client connects to redis commander server - maybe not a redis connection error but something else?
