### ISSUE TITLE
Redis Commander does not work behind Codespaces public URL

### ISSUE THREAD

**Issue by themizzi** [joeferner/redis-commander#466]
This is a bit of a goofy one, but I'm trying to use redis commander behind GitHub codespaces. There is an issue with GitHub codespaces where you cannot use a root path of `/signin` behind its public URLs. That URL is trapped behind their proxy. Redis commander has a `/signin` route and all of the requests to it fail making redis commander crash when behind codespaces. I'd be happy to help work on a resolution for this.

**Comment by sseide** [comment]
added with 6e75f95
can you test the new code/docker image?

**Comment by sseide** [comment]
should be fixed with latest release 0.8.0.
Please reopen if not.

**Comment by themizzi** [comment]
@sseide I am no longer with the org I was with when this request was submitted. I will need to setup a new environment to test this with, but I am unsure when I will be able to get to it.
