### ISSUE TITLE
update Ingress to support kubernetes 1.22 or later

### ISSUE THREAD

**Issue by jkirkham-ratehub** [joeferner/redis-commander#469]
The Ingress resource API versions `extensions/v1beta1` and `networking.k8s.io/v1beta1` have been deprecated for quite a while and in kubernetes 1.22 these API versions will be removed -- `networking.k8s.io/v1` has been available since kubernetes 1.19.

To support kubernetes 1.22 or later the Helm chart needs to be updated to use the `networking.k8s.io/v1` for [Ingress ](https://github.com/joeferner/redis-commander/blob/master/k8s/helm-chart/redis-commander/templates/ingress.yaml)resources.

**Comment by sseide** [comment]
yes, you are right. can you create an PR where the ingress API is configurable via variable? Some older systems like OpenShift 3 need the old definition...
The newer API can be the default nonetheless.

**Comment by jkirkham-ratehub** [comment]
PR is available here:  https://github.com/joeferner/redis-commander/pull/470
