### ISSUE TITLE
Getting this error....       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by jayeconsult** [joeferner/redis-commander#473]
Thanks for the brilliant tool...

But I am getting this error... when running

➜   redis-commander
Using scan instead of keys
No Save: false
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:8081
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at doListen (net.js:1413:7)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by sseide** [comment]
`EADDRINUSE` is the error code from the operation system (independent of programming language used) that the port 8081 is already used by another program.

either stop the other program using this port or use a different one for redis commander.

**Comment by jayeconsult** [comment]
> `EADDRINUSE` is the error code from the operation system (independent of programming language used) that the port 8081 is already used by another program.
> 
> either stop the other program using this port or use a different one for redis commander.

Big thanks, it works now...
