### ISSUE TITLE
Please add JSON viewer to ReJSON viewer

### ISSUE THREAD

**Issue by devleaks** [joeferner/redis-commander#477]
Hello,
Thank you very much for this handy tool.
Would it be possible to add a JSON tree viewer to the ReJSON viewer?
The simplest the better. I found [this one](https://github.com/LorDOniX/json-viewer/).
Thank you.

**Comment by sseide** [comment]
this app already includes an json viewer but this is used with strings or hash fields only, not with rejson (https://github.com/abodelot/jquery.json-viewer)

When you have time to add a PR using it with ReJSON too it is welcome...

**Comment by devleaks** [comment]
See https://github.com/joeferner/redis-commander/pull/478. Thanks P.
