### ISSUE TITLE
lossless-json internals bleed to display

### ISSUE THREAD

**Issue by devleaks** [joeferner/redis-commander#479]
Hello,
While working on json tree display in redis-commander, I noticed that some undesirable data appears in tree. (See pic below, losslessNumber and isLosslessNumber are definitely not mine.)
I suspect it comes from lossless-json. If you are trying to only solve the BigInt issue with JSON, [this solution](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json) is simple and elegant and does not require a special parser. I noticed you're working on it these days, so it may just be a temporary issue, I just bring it to your attention. You get to this when you're trying to view a tree of a redis string value (not ReJSON), string value that contains valid json, and json that contains numeric values; problem does not exhibit when json has string only values).

Best regards.

![jsondisplay](https://user-images.githubusercontent.com/6030167/168777488-57a4f2a3-82fd-4e82-9673-e7dfdb13bf77.png)

**Comment by sseide** [comment]
Tested with latest version itself i do not see this behaviour myself. There big number support is fully working since 0.8.0 without a problem, just displaying the number in blue (as number, not string).

Can you please send me the data stored inside Redis when you get it with redis-cli or similar.

best regads

**Comment by devleaks** [comment]
Hi.
Add a key of this **string** with the following content: (sorry, number roundings from imperial to metric conversion!) 
```
{
    "acmodel": "ACJ320neo (Corporate Jet version)",
    "properties": {
      "length": 37.57269599999999,
      "wingspan": 35.798759999999994
    }
}
```
and hit «View mode tree»:

![ac](https://user-images.githubusercontent.com/6030167/169011160-531e7471-2900-422e-b044-5dbda1d451be.png)

**Comment by sseide** [comment]
oh - you are right, there is a problem. Just tested with large integers not displayed right as javascript "number" before and they are working now...
Did not test with floats...

**Comment by sseide** [comment]
updated code and fixed version is available on github master branch and as latest docker image on Github Registry.
Do you mind checking with your data?

**Comment by devleaks** [comment]
Looks ok to me. With npm.
Could you explain why yarn does not work for you? (I'm a yarn guy.)
P.

**Comment by sseide** [comment]
i think it is an old restriction no one reevaluated.

It was connected to the locations yarn installed packages to - not every time inside the local "node_modules" folder. That together with the way packages where loaded/located to send them to the browser (as client side js) did not work reliably.

The code to get the path to the package files for sending it to the browser was changed and it might work now with yarn again...
