### ISSUE TITLE
Redis commander in docker connect to Redis Sentinels with TLS ca

### ISSUE THREAD

**Issue by brawo1994** [joeferner/redis-commander#482]
Hello
Can you show example configuration and command to run Redis Commander in Docker to connect Redis Sentinel TLS?

Config Redis Sentinel:

port 0
tls-port 26380
tls-cert-file "/apps/redis/certs/TEST.cer"
tls-key-file "/apps/redis/certs/TEST.key"
tls-ca-cert-file "/apps/redis/certs/bundleTEST.cer"
tls-auth-clients no
tls-replication yes
requirepass secret_password
sentinel auth-pass test_master secret_password

I can't figure out how and where exactly to pass bundleTEST.cer to the container...

**Comment by sseide** [comment]
To connect to an TLS enabled redis server use env variable `REDIS_TLS=true`.
This setting enables TLS but does not enforce specific TLS certificates (no certificate pinning).

To use custom server certificates you need to pass your own `local.json` into the container with all connection information set together with the full "tls" object as described in the NodeJS runtime documentation for 
```
{
  "connection": [
    {
      "label": "redis-tls",
      "sentinels": "sentinel-ip:26380",
      "sentinelName": "mymaster",
      "password": "<redis-server-pw>",
      "sentinelPassword": "<sentinel-pw>",
      "tls": {
        "ca": "-----BEGIN CERTIFICATE-----\nhere PEM encoded ca cert as one long line==\n-----END CERTIFICATE-----",
      }
    }
  ]
}
```

Side note - there is a PR in progress to allow setting certificate information via command line params or env vars too (#514)

**Comment by sseide** [comment]
Or have you tried to set the tls object directly as Env var?

To trust a specific CA certificate set REDIS_TLS env var to a json string with
```
{"ca":"<content_of_ca_cert_pem_file_with_linebreaks_as_\n"}
```

Either provide your own local.json or set redis server ca cert via env var as JSON stringified object.
