### ISSUE TITLE
USE_SCAN=false, --use-scan=false and --root-pattern='pattern*' seem not to be working

### ISSUE THREAD

**Issue by JESii** [joeferner/redis-commander#493]
I need to be able to review specific top-level key stacks in my production redis DB. We keep each days' data around for a while so at any one time there are close to 1MM keys. However, when I want to trouble-shoot/research, I only want to look at one days' data -- the current one which is usually only about 40K keys. Loading all 1MM keys takes 15-20 minutes, whereas loading my 40K keys is very short: less than a minute.

Using the SCAN command even with MATCH is not the way to do this as, according to the redis docs (https://redis.io/commands/scan/):
"It is important to note that the MATCH filter is applied **_after elements are retrieved from the collection_**, just before returning data to the client". [my emphasis] Obviously, reading the whole DB before filtering buys us nothing.

I tried using the --root-pattern option, along with --use-scan=false, but it looks like commander may now be forcing the use of SCAN, as I got this message: `Using scan instead of keys`

Our production redis services are exposed on port 6380 and and I'm running redis-commander in a docker container like so:
```
export USE_SCAN=false
docker run --rm \
  -p 8181:8081 \
  -e NODE_TLS_REJECT_UNAUTHORIZED=0 \
  -e REDIS_HOST=host.docker.internal \
  -e REDIS_PORT=6380 \
  -e REDIS_TLS=true \
  -e REDIS_PASSWORD=$1 \
  -e --use-scan=false \
  -e --root-pattern='etl-namespace*' \
  rediscommander/redis-commander:latest
```
 here's the log from running that:
```
Creating custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --redis-port 6380 --redis-host host.docker.internal --redis-tls --redis-password <set>
Using scan instead of keys
No Save: false
(node:7) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
Redis Connection host.docker.internal:6380 with TLS using Redis DB #0
```

I know that using KEYS on a production redis server can cause problems -- but as developers who are responsible for supporting production, I think we are smart enough to make an informed decision as to when we should use KEYS. After all, redis-commander is primarily a tool for developers.

But I'm only willing to do that if I can limit the query to only that one key-stack that I'm interested in.

So... I'm curious to know what went wrong with my setup so that I can use KEYS with a rootPattern to limit that impact and see the keys that I'm interested in.

Thanks for a great utility!

**Comment by sseide** [comment]
Hi,

looking at the docker run command you seem to set the `-use-scan` and `--root-pattern` parameter not as application parameter but as environment variables. the `--xyz` things are command line switches only and have no effect setting them this way.

please try with their environmant variable equivalent `docker run -rm -e ROOT_PATTERN='etl-namespace*' -e USE_SCAN=FALSE -e ...`

**Comment by JESii** [comment]
Thanks, @sseide I'll take a look today

**Comment by JESii** [comment]
Thanks; done. have a great day!
