### ISSUE TITLE
[helm chart] Connection to sentinels support 

### ISSUE THREAD

**Issue by VuiDJi** [joeferner/redis-commander#510]
Hi!
Please tell me how it is possible to use env parameters to pass values for specifying sentinel servers when deploying via helm chart?
Thank you!

**Comment by VuiDJi** [comment]
I figured out how to do it:
`env: [{name: SENTINELS, value: "redis-node-0.redis-headless:26379,redis-node-1.redis-headless:26379,redis-node-2.redis-headless:26379"}]`

It's good that we managed to connect sentinels in this way, however, it would be very convenient if they could be specified immediately in values.yaml file, as it is done with "hosts" param.

**Comment by sseide** [comment]
As i do not have that much time right now - a change request is welcome.
You can look at the docker-startup file how hosts are handled and with an updated dokumentation i'll accept it.

Best regards
