### ISSUE TITLE
SERVICE_USERS added to root group

### ISSUE THREAD

**Issue by dima-aronov** [joeferner/redis-commander#524]
In the context of the dockerfile, the command
"
adduser "${SERVICE_USER}" -h "${HOME}" -G root -S -u 10000 
"
The SERVICE_USER is added to the root group which may pose a potential risk.
Would it be possible to change the group to {SERVICE_USER} or any other lower privilege user.

Thanks !

**Comment by sseide** [comment]
No, it is no security risk and needed to be able to run inside OpenShift without any problem.
You can read more about it here: 

* https://docs.openshift.com/container-platform/4.13/openshift_images/create-images.html

Within linux systems group "root" does not give you any additional access rights. Here systems use "wheel" or "adm" group for this.
