### ISSUE TITLE
New release any time soon?

### ISSUE THREAD

**Issue by xr09** [joeferner/redis-commander#531]
I'd like to use redis-commander latest version with all the new fixes, are you planning to release a 0.8.2 or 0.9 version anytime soon?

I know I can pull **latest**, but it's not optimal since I'd prefer to keep my manifests reproducible.

**Comment by sseide** [comment]
yes - as soon as new cluster support is tested and othres having problems with "latest" with it say its ok....

**Comment by xr09** [comment]
Awesome, thanks @sseide!

**Comment by ilteoood** [comment]
@sseide any update about this? After a year, the situation is still the same
