### ISSUE TITLE
Unable to sign-in with HTTP_PASSWORD_HASH

### ISSUE THREAD

**Issue by gaby** [joeferner/redis-commander#577]
Unable to login using the `HTTP_PASSWORD_HASH` environment variable after generating a hash using the recommended method here:  https://github.com/joeferner/redis-commander#generate-bcrypted-password-hash

The validation code should be something like this:

```javascript
if (config.get('server.httpAuth.passwordHash')) {
  validPass = await bcrypt.compare(
    String(req.body.password), 
    String(config.get('server.httpAuth.passwordHash'))
  );
}
```

It's currently not awaiting, see here: https://github.com/joeferner/redis-commander/blob/master/lib/app.js#L240

This issue was previously reported years ago, and it still doesn't work. Here https://github.com/joeferner/redis-commander/issues/434

Ping @joeferner @sseide @mrohr

**Comment by sseide** [comment]
changed code to explicit sync comparison and make timing attacks harder (was possible before on user name check).
Its strange as it was working on on local environments, hence issue was closes as non-reproducible as there was no feedback given.

**Comment by gaby** [comment]
@sseide Thanl you, will test today/tomorrow and report back.

**Comment by gaby** [comment]
@sseide Seems better now. The main problem is that when using the hash provided by bcrypt in a docker-compose yml file you have to escape the `$` with `$$`.
