### ISSUE TITLE
ARM64 docker image

### ISSUE THREAD

**Issue by francescor** [joeferner/redis-commander#578]
Hi there!
Thanks for your work!

I would like to request a release of the image for the ARM64 architecture. Currently, only the x86_64 version is available, and having an ARM64 option would be incredibly helpful for us to we can move to cheaper ARM-based systems.

Thank you for considering this!

**Comment by sseide** [comment]
its already there for a longer time:
https://github.com/joeferner/redis-commander/pkgs/container/redis-commander
just check "OS / Arch" tab.
