### ISSUE TITLE
Add ability to monitor multiple instances of redis using a single version of redis-commander

### ISSUE THREAD

**Issue by tvernon** [joeferner/redis-commander#81]
After having multiple users mention needing to run multiple instances of redis-commander in order to perform admin processes on multiple redis instances, I am going to look into adding support for monitoring multiple redis instances from a single instance of redis-commander.

**Comment by Soullivaneuh** [comment]
Hi @tvernon.

I tried with following options: `--redis-host redis --redis-db 0 --redis-db 1`

But this only show the database `0` and startup. What I am missing?

**Comment by Soullivaneuh** [comment]
Finally found a way with .redis-commander config:

```json
{
  "sidebarWidth": 250,
  "locked": true,
  "CLIHeight": 50,
  "CLIOpen": false,
  "default_connections": [
    {
      "label": "default",
      "host": "redis",
      "port": "6379",
      "password": "",
      "dbIndex": 0
    },
    {
      "label": "session",
      "host": "redis",
      "port": "6379",
      "password": "",
      "dbIndex": 1
    }
  ]
}
```
