### ISSUE TITLE
client temporarily uses an enormous amount of memory on initial load

### ISSUE THREAD

**Issue by Supermathie** [joeferner/redis-commander#85]
I just set up a fresh and redis-commander 0.1.0 and pointed it at our database.

Looks great, except that when initially loading keys in a DB the client pauses for a while and chews up about 4GB of extra memory (in Firefox and Chrome). After the keys load, memory usage drops right back down and it again responds to input.

From that point on, everything's better (until you reload the page/refresh the keys)

Our database isn't huge, it only has 28K keys.

It may have to do with the large(?) number of keys that aren't folded; at least 10K appear in the root of the inspection tree.

What else would you like from me to diagnose this issue further?

**Comment by sseide** [comment]
as said #97 will have more informations for this... you can either define a root pattern or chekc out using `--use-scan` cli param or config value. thats using the `SCAN` command instead of `KEYS` that is not having such a negativ impact...
