### ISSUE TITLE
Add JSON viewer to value window

### ISSUE THREAD

**Issue by Koed00** [joeferner/redis-commander#86]
Since most Redis values are in JSON these days, a JSON visualizer would make my work so much easier.

**Comment by sseide** [comment]
The feature requested is available with latest version. Select a entry with JSON and press button "View mode tree" an the upper right side to toggle between edit mode and json view. (granted - "View mode tree" is not the best name but feature is there...)

If there is something missing at the implementation feel free to reopen issue with an updated description.
