### ISSUE TITLE
Tree collapses on refresh

### ISSUE THREAD

**Issue by plainas** [joeferner/redis-commander#90]
I believe this is not the intended/optimal behavior.

Each time I click refresh I have to manually expand the tree. This is very unpractical

**Comment by ChillarAnand** [comment]
I just stumbled on this issue. Any updates on the issue or are there any work arounds?

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
