### ISSUE TITLE
How to delete server without webadmin permanently?

### ISSUE THREAD

**Issue by raitucarp** [joeferner/redis-commander#92]
I confuse, when I add a server it will be there forever. How to delete it permanently?

**Comment by kalail** [comment]
bump

Just ran into this problem.

**Comment by nlrooat** [comment]
Thanks @fforres!

**Comment by fforres** [comment]
Nvm guys :)

**Comment by decebal** [comment]
thanks for the tip; would be nice an option to clear the cache

**Comment by sseide** [comment]
Besides clearing up the configuration file it is possible to remove servers via UI with current version.
Additionaly a command line param to start with emtpy server list is available too.

Closing ticket as this should not be a problem anymore.
