### ISSUE TITLE
Cant reach server, redis-commander broke [WORKAROUND SOLUTION] 

### ISSUE THREAD

**Issue by fforres** [joeferner/redis-commander#93]
If you cant connect to a server, redis-commander breaks and does not show a single redis instance.

While we wait for the official solution, you can solve the problem deleting the server manually.

Navigate into the User folder (/home/<user>) and into the .redis-commander file:
Once in there, delete the object that points to (or has the data of) the server you want to delete.

An example, this:
{"sidebarWidth":"617","locked":"false","CLIHeight":"94","CLIOpen":"false","default_connections":[{"host":"127.0.0.1","port":"6380","password":"","dbIndex":"0"},{"host":"127.0.0.2","port":"6381","password":"","dbIndex":"0"}]}

Ends up looking like this:
{"sidebarWidth":"617","locked":"false","CLIHeight":"94","CLIOpen":"false","default_connections":[{"host":"127.0.0.1","port":"6380","password":"","dbIndex":"0"}]}

Hope you can fix this soon, the tool is awesome!

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
