### ISSUE TITLE
No command line output

### ISSUE THREAD

**Issue by Rinum** [joeferner/redis-commander#96]
I'm on Ubuntu v13.04. I've installed redis-commander.

I don't see any output from entering "redis-commander --help". Any idea why?

Example:

root@localhost:/srv/wwwi# redis-commander
root@localhost:/srv/www# redis-commander --help

Nothing shows up

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
