### ISSUE TITLE
Do not run KEYS by default

### ISSUE THREAD

**Issue by ssimeonov** [joeferner/redis-commander#97]
Any Redis administration tool should be aware of its impact on the instance it is managing. Redis is single-threaded. Running KEYS by default can make the server unavailable for long periods of time.

Technically, this may be an enhancement but logically it is a bug. Now a redis-commander admin needs to be aware of (a) the number of keys in Redis and (b) the client access requirements before deciding whether they can risk connecting `redis-commander` to the node.

For example, we have Redis databases with > 10M keys. We could never even risk connecting `redis-commander` to those. `Redsmin` is doing the right thing by asking admins to provide key patterns they resolve.

**Comment by pablote** [comment]
It should be mentioned that using the SCAN command instead of KEYS is the proper way to go, either filtering with a pattern or not. If pointed to the right direction in the codebase I could probably get that implemented.

**Comment by SebastienTainon** [comment]
Here is a PR to add a root pattern to the KEYS command: https://github.com/joeferner/redis-commander/pull/197

@pablote, you could use this PR to modify it to a SCAN command :wink:

**Comment by sseide** [comment]
changed default values to use redis SCAN instead of KEYS if nothing else requested via env var/cli param/config file (commit ef0589671e389b67720cd321ee6ab9505cfe8824)

Will close issue now. If there are some other requests feel free to open a new issue...

**Comment by JESii** [comment]
@pablote I don't think using SCAN to filter the DB is the way to go. According to the redis docs at https://redis.io/commands/scan/

"It is important to note that the MATCH filter is applied _**after elements are retrieved from the collection**_, just before returning data to the client." [my emphasis]

In other words, you read the whole d**n DB which is exactly what we do not want!
